### ISSUE TITLE
convert_lead() endpoint doesn't seem to honor dynamic auth

### ISSUE THREAD

**Issue by hoprocker** [django-salesforce/django-salesforce#106]
Should it? From `salesforce/utils.py`:

```
settings_dict = settings.DATABASES['salesforce']
## dot dot dot
soap_client.login(settings_dict['USER'], settings_dict['PASSWORD'])
```

Looks like this method has a totally separate authentication mechanism. Is this because we can't use the same access_token with beatbox/SOAP?

**Comment by philchristensen** [comment]
Yeah, this is generally a convenience method. Unfortunately there's no way to do it in pure REST (see #96), and there's a bunch of noteworthy exceptions.

This is less an indication of a bug or shortcoming in django-salesforce, and more an indication of the idiosyncrasies of the Sakesforce API.

It may not be possible to have a method that does all things for all people, but I'd be very interested in a solution that gives a more intelligent error in the case of misconfiguration.

Since django-salesforce is never going to be particularly performant due to the realities of web requests, I'd also prefer a solution that uses introspection to determine the default action.

**Comment by philchristensen** [comment]
Sorry, the second half of my comment above was so nonsensical because I was talking about a different issue.

As for this issue, yeah, the beatbox library uses SOAP, which is why it can access this conversion routine where the regular REST stuff can't.

**Comment by hoprocker** [comment]
Finally got a chance to look around and figure something out for this -- the same call that gets the `access_token` and `instance_url` also gets an `id` url, which gives access to the all the available endpoints (including for SOAP). This can be used like so:

```
from django.db import connections

soap_client = beatbox.PythonClient()
soap_client.useSession(connections['salesforce'].sf_session.auth.dynamic_token, soap_url)
```

I'm not trying to drag this out, but it seems like if you're going to allow the `convert_lead()` endpoint, and you're also facilitating dynamic authentication -- both of which are GREAT features!!! -- it seems natural to facilitate letting them work together. I bet you could get by with something as simple as saving the `id` url on the auth object, then creating the SOAP url on-demand and saving it when needed. (I've got my own simple hack for this, but it should be cleaned up a lot before entering general use.)

**Comment by philchristensen** [comment]
Oh, I see, you're saying we can use the existing security token from the REST connection to make the SOAP connection. Hmm, that's interesting...

**Comment by galsilb** [comment]
This could be more needed then you think. I'm trying to do different APEX service calls to Salesforce api, and this whole process could have been much simpler if I could inject the access token to the soap connection.

**Comment by hynekcer** [comment]
You are right. The first step is easy. What if the token expires accidentally at the least appropriate time? I also implemented bulk API and different auth methods in a development branch, then it was more complicated to make it all work together without unadvised changes. Not so easy. I going to commit it.

**Comment by hynekcer** [comment]
Both tokens for SOAP API and REST API are currently different, the have only the same size. If I replace one of them, it causes error. I think that both tokens were the same last year, but currently not.
@hoprocker Can you verify i again that they are replaceable?

**Comment by galsilb** [comment]
@hynekcer can you show me the changes you made on `sf_session.auth`?
I need to be able to grab the access token from the connection.

**Comment by hynekcer** [comment]
Currently you can get the token this way

    from django.db import connection
    # the connection name can be a variable if you e.g. update data between two SFDC instances
    auth_obj =  connections['salesforce'].sf_session.auth
    if auth_obj.dynamic_token:
            access_token = auth_obj.dynamic_token
        else:
            access_token = str(auth_obj.authenticate()['access_token'])
    instance_url = auth_obj.instance_url    # this is also dynamic

If this access token for REST API is useful also for SOAP API still, please inform me. (The code is not nice, but I don't want to commit plain refactoring before it is really useful. The function "authenticate()" usually returns the cached value.)

**Comment by philchristensen** [comment]
Closing this issue, but added a link to it from the wiki here under important issues:

https://github.com/django-salesforce/django-salesforce/wiki#important-issues

**Comment by hynekcer** [comment]
I have fixed this in one of my development branches last week. It only needs to reorganize commits /so that every commit does one thing and does it correctly without commits "Oh, I forgot..") The current ugly branch is [hynekcer django-salesforce bulk](https://github.com/hynekcer/django-salesforce/tree/bulk) (current head 41cd492a332) It implements **Bulk create** and bulk update operations via SOAP API. It is helpful for speed and governor limits. 

If you want Python 2 + 3 compatible code, I recommend my `pip install git+https://github.com/hynekcer/beatbox-davisagli.git@7f628a789cba#egg=beatbox` (used by tox.ini) instead of PyPI until it will send and accepted to an important repository. *(A big part of my patch is still in the original author's repository [superfell/Beatbox](https://github.com/superfell/Beatbox). Many authors have crated the Python client that is the highest layer in beatbox on PyPI. (Its repository is [davisagli/beatbox](https://github.com/davisagli/beatbox/).) I wrote also [a patch for it](https://github.com/hynekcer/beatbox-davisagli/tree/python3). I wish the beatbox package on PyPI would be maintained again and a link to its source repository can be found here. Therefore I wish both authors agree each other some way earlier than I would prefer one of them so much that the agreement will be more complicated.)*

When I fixed beatbox I found that I had made different mistakes twice in May, that the tokens seemed they could not be substituted. I am sorry.
