### ISSUE TITLE
Where is 'models' attribute?

### ISSUE THREAD

**Issue by tomdavidson** [django-salesforce/django-salesforce#110]
Im having a bear of a time tracking down why my management command will not work, similar code works from manage.py shell. Its fully described in the SO link at the bottom, but the error is:
```python2
SalesforceModel(with_metaclass(salesforce.models.SalesforceModelBase, models.Model)):
AttributeError: 'module' object has no attribute 'models'
```
Looking though django-salesforce, where is 'models' anyway?

http://stackoverflow.com/questions/31522701/correctly-import-in-django-management-command

**Comment by dalem1959** [comment]
When I have run into a problem like this in the past it is because I was 
using a newer version of Django that created both a project level and 
application level directories.  The top level contained the manage.py 
file and the lower level contains the setup.py and is where I placed the 
models.py which I created using inspectdb (in this example the project 
and app are named "ds"):

>     $ ls -R
>     db.sqlite3    ds        ds2        manage.py
>
>     ./ds:
>     __init__.py    models.py    settings.py    urls.py wsgi.py

When I tried to filter on objects (Cases, Accounts, etc) I would get the 
error you noted.  I determined the problem was that I needed to include 
my app directory name in list for "INSTALLED_APPS" in settings.py.

Dale

**Comment by tomdavidson** [comment]
Thanks Dale. I have 'util' in the INSTALLED_APPS lists. Do I need 'util.management.commands' instead? I also tried adding the management/commands/oauth.py to the existing authentication module in a path experiment - same error.

The ORM layer for the API is pretty interesting to me. salesforce does not have its own model, but imports django.db model?

**Comment by hynekcer** [comment]
Which module "'has no attribute 'models"? Yours? You should not use the line `class SalesforceModel(with_metaclass(....)...):` copied in your code. It looks incorrectly in your traceback.

`SalesforceModel` is a customized `django.db.models.Model` and it should be used as base of your models that use the SFDC database. The alias of SalesforceModel is `salesforce.models.Model`. The import `from salesforce import models` can be used simply instead of `from django.db import models`, if you find all names important for you copied there.

Do you try to interfere your oauth with Salesforce authentication or it is only for your users?

**Comment by hynekcer** [comment]
I answered to [your question at SO](http://stackoverflow.com/q/31522701/448474) how you can write a simplified demo code of the problem and what should be fixed in the code before committing anything. An issue should be reprodicible (even hypothetic issue like "if you repeat this continuously one day you get at least one error")
