### ISSUE TITLE
Querying date ranges in SOQL

### ISSUE THREAD

**Issue by chromakey** [django-salesforce/django-salesforce#130]
custom_date_field is just a substituted name for a date field I'm actually using.  

```
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)

leads = Lead.objects.filter(custom_date_field__range=(yesterday, today))

for lead in leads:
    print(lead.id)
```
returns:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/chromakey/.virtualenvs/my_project/lib/python3.4/site-packages/django/db/models/query.py", line 141, in __iter__
    self._fetch_all()
  File "/Users/chromakey/.virtualenvs/my_project/lib/python3.4/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/chromakey/.virtualenvs/my_project/lib/python3.4/site-packages/salesforce/backend/query.py", line 252, in iterator
    cursor.execute(sql, params)
  File "/Users/chromakey/.virtualenvs/my_project/lib/python3.4/site-packages/salesforce/backend/query.py", line 407, in execute
    response = self.execute_select(q, args)
  File "/Users/chromakey/.virtualenvs/my_project/lib/python3.4/site-packages/salesforce/backend/query.py", line 456, in execute_select
    return handle_api_exceptions(url, self.session.get, _cursor=self)
  File "/Users/chromakey/.virtualenvs/my_project/lib/python3.4/site-packages/salesforce/backend/query.py", line 142, in handle_api_exceptions
    raise base.SalesforceError(data['message'], data, response, verbose)
salesforce.backend.base.SalesforceError: 
Lead.custom_date_field__c BETWEEN 2015-09-01 AND 2015-09-02
                                 ^
ERROR at Row:1:Column:968
unexpected token: 'BETWEEN'
```

```
print(leads.query.get_compiler('salesforce').as_sql())
```
returns:
```
('SELECT <<my_lead_fields>> FROM Lead WHERE Lead.custom_date_field__c BETWEEN %s AND %s', (datetime.date(2015, 9, 1), datetime.date(2015, 9, 2)))
```

A cursory search of the SOQL documentation doesn't seem to turn up anything on using the BETWEEN clause.  From what I can tell, the correct SOQL would be:

```
('SELECT <<my_lead_fields>> FROM Lead WHERE Lead.custom_date_field__c > %s AND Lead.custom_date_field__c < %s', (datetime.date(2015, 9, 1), datetime.date(2015, 9, 2)))
```

You guys do great work on this library (and update it constantly).  If this is indeed the case that the range lookup doesn't work, and I'm not just missing something, I'd like to write a pull request for it.  I'm just not sure where I should stick the custom lookup code, but if you steer me in the right direction I'll take the time to do it.  Thanks!

**Comment by philchristensen** [comment]
Congrats, you must be the first person to attempt a range lookup query!

I'm not sure how easy/hard it will be to implement this, but here's where it comes from in the Django base SQL compiler:

https://github.com/django/django/blob/stable/1.7.x/django/db/models/sql/where.py#L249

And here's the method that takes care of it in django-salesforce:

https://github.com/django-salesforce/django-salesforce/blob/master/salesforce/backend/compiler.py#L361

This file is pretty complicated because since Django 1.8, the DB backends have been pretty radically refactored:

https://github.com/django/django/blob/stable/1.8.x/django/db/models/sql/where.py

**Comment by hynekcer** [comment]
You are right that the operator BETWEEN is not implemented in SOQL. It implements only some very special cases like THIS_WEEK or LAST_MONTH that are not useful for Django. Many features in django.db are there in my opinion only because they are implemented in SQL and it is very easy to suport them. We implement even a few very complicated features by a long code, if they are very important and they can not be easily substituted or the substitution would be very inefficient.

Your code can be easily replaced by

    Lead.objects.filter(custom_date_field__gte=yesterday, custom_date_field__lte=today)

or even

    Lead.objects.filter(custom_date_field__in=(yesterday, today))

because there is no other day value between yesterday and today.

**Comment by chromakey** [comment]
That's a fair point about using the gte and lte lookups in conjunction, I don't know why I didn't think of that.  I'll take a look at doing something for the range lookup over the weekend and let you know if I'm able to do anything with it or not.  Thanks guys.

**Comment by chromakey** [comment]
Added a PR:
https://github.com/django-salesforce/django-salesforce/pull/131
