### ISSUE TITLE
Why not make SF_LAZY_CONNECT True by default

### ISSUE THREAD

**Issue by MounirMesselmeni** [django-salesforce/django-salesforce#147]
I think it's not a good idea to make connection failure to Salesforce url broke the whole system, what's bad on making this lazy by default?

**Comment by chromakey** [comment]
Just chiming in that I'm wondering the same thing.  When I don't have lazy loading turned on, if the credentials of the Salesforce user I have in the system have changed and I start the server, it will result in the app not starting and typically results in the Salesforce user being locked out due to exceeding the number of invalid logins.

**Comment by philchristensen** [comment]
The default behavior matches the behavior of Django's ORM when a database is offline.

**Comment by MounirMesselmeni** [comment]
I agree it matches the ORM behavior of Django, but is it really like a database connection? I don't think so.
I believe most of the people using django-salesforces for some views or application logic but not everywhere as a real database engine.

Now, why should my periodic celery tasks who runs at 2:00 am fail and send hundreds or thousands of errors if salesforces api is down and considering that these tasks are not using salesforces? Should they fail if my database connection is broken, absolutely yes.

I don't believe it's right to compare this with the default behavior of Django ORM, and feel free to correct if you still think I'm wrong.

**Comment by philchristensen** [comment]
If you're running in prod, there's any number of defaults you should be overriding.

**Comment by hynekcer** [comment]
@MounirMesselmeni I think that it is in the same as if you stop your local SQL server and start Django app, not worse, it is only more unexpected and totally out of your control. Do you agree? Is it solved by `SF_LAZY_CONNECT` completely?

@chromakey Do you say that you can fix it by `SF_LAZY_CONNECT = True`? I think the opposite. With the default settings the app dies and only one login attempt should be done. With the lazy connect you be in the problem due to many attempts.

It is complicated because there had to be a configurable delay before this shouldn't be done any next attempt to connect. If I expect that you can run the app e.g. in two processes and you use  "Maximum invalid login attempts = 3" recommended by SFDC you can not do the next try sooner than before the Lockout effective period. (Salesforce Setup / Security Settings / Passord Policies / Lockout effective period) Anyway you get the same delay. I use a separate Salesforce account for the web server, so nobody would be affected by that locking. Especially on a sanbox it is a cheap soludion. My resume is that a fix can be useful for a development but nothing useful is possible for a web server.

You can create a special user profile for the web server user (.../ Manage Users / Profiles / Password Policies) and set apropriate values and restrict the IP range a few items above.

**Comment by hynekcer** [comment]
@chromakey Hmm. A fix with a short delay approximately 3 minutes before the next login can be used, in order to not look like a DOS attack at SF. Otherwise the IP could be blocked, that's worse. Than you can live save with 10 attempts and 15 min lock.

**Comment by MounirMesselmeni** [comment]
@hynekcer yes exactly it's out of my control and this why I was thinking it's good to change it. If I'm using many APIs (Salesforce, Paypal, Facebook ...) and my application is down because one of these services is down I don't think it's the best way to do so.
I appreciate the fact I can control this via `SF_LAZY_CONNECT` which solve my issues and many thanks for your time.
