### ISSUE TITLE
Add __version__ to __init__.py

### ISSUE THREAD

**Issue by jschneier** [django-salesforce/django-salesforce#153]
Almost every package (aside from Django actually which has `.VERSION`) specifies a `__version__`. This library should do the same.

**Comment by philchristensen** [comment]
Patches are welcome!

**Comment by jschneier** [comment]
Great! I wasn't sure because you have `get_tagged_version` in `setup.py`. Although there hasn't been a `git tag` applied since 0.6.2.1.

**Comment by philchristensen** [comment]
Actually, since I've been using GitHub to do the releases, the tag format dropped the 'v', so they're at the bottom of the list.

**Comment by philchristensen** [comment]
Closed by #155 (thanks @hynekcer!)

**Comment by philchristensen** [comment]
Huh, I guess only commits close PRs

**Comment by hynekcer** [comment]
I'm afraid that something is broken with the last three packages on PyPI.
The last visible package is 0.6.2.1 in the index. The new packages 0.6.2.2, 0.6.2.3 and 0.6.3 can be found by direct writing URL but without description README. It can be related to missing letter "v" in the tag because the last tag sequence is not monotonic.

**Comment by philchristensen** [comment]
Gah! Okay. I'll get this fixed ASAP, sometime this week.
