### ISSUE TITLE
Status code 413 'Error: Request Entity Too Large: head' 

### ISSUE THREAD

**Issue by bryancolligan** [django-salesforce/django-salesforce#164]
When querying the Account standard object that has 400 custom fields on the object.  this creates an inconsistent error retrieving data for the django-salesforce module.  Is there any feedback or strategies on how to approach this?  It seems like a request size limitation on the salesforce side. Any suggestions or feedback would help.

**Comment by hynekcer** [comment]
It is interesting that Salesforce objects with around 400 fields are reported frequently in questions about error code 413 on different sites even not related to Python. I can optimize the query compiler by approximately 15 %, for huge queries. Normal queries should not be optimized because readability is also important. Improvement by 2 % is trivial. How many removed fields would help you? (How many percent you need?)

The number of fields could be (theoretically) restricted by `values(fields)` or `values_list(fields)` query sets, but it was implemented for Django <= 1.7.x  by different django-salesforce versions <= 0.6.9. Now, a few days after 0.6.9 it works for Django 1.8 - 1.10 in a development version for, but it is based on a so different code, that it requires also practical testing before release 0.7.  

I implemented bulk insert and update on queryset, both work by SOAP API in version 0.6.9. I can use SOAP also for huge queries. That could increase the available query size by another 25 %. A time estimate could be this winter.

What are your versions of Django-salesforce, Django, Python? (I see that the error 413 is not reported correctly now. The fix is easy.) Is the WHERE condition simple or it is also very complicated, e.g. with hundreds values?

**Comment by philchristensen** [comment]
I'm not sure it's worth optimizing this case. 400 fields seems pretty likely to be hitting the 16k limit of HTTP headers that Apache uses, for example. It's not literally part of the spec, but it's often set on webserver implementations.

Why on earth would you ever have an object with that many fields, in practice? It seems like poor design. It's such a specialized case I'd just make multiple models.

-Phil
sent from my phone

**Comment by hynekcer** [comment]
I also can't imagine people that could be happy with a so big Account object. This could easily fail on the SF web if all fields are visible. On the other way, I can not imagine how you could see the Status code 413 in django-salesforce before the today's bug fix. (related to an exception in error messages code) Good catch. Thanks for the report.

Is the improvement in the current master branch by 2.5% useful for you? Otherwise I'm going to remove it otherwise soon without replacement.

I have though earlier that query sets like `Foo.objects.filter(id_in=very_long_list)` could fail with http 413 error if the list of IDs is approximately 570 items long. It can not be sometimes easily split to more queries if it is combined with some aggregation. This could be probably improved by SOAP API by 100%. (higher estimate thanks to calculation of unfavorable url encoding of short strings with apostrophes)

The compiler optimization by removing "TableName." would be really bad because a custom SF table Foo__c can contain a custom field Foo__c that may not be a part of Django models. Django can not therefore know about that ambiguous names whether the table names before field names can be simply omitted or not. The current convention, that table names are used always, is useful for parsing for machine generated queries.

**Comment by bryancolligan** [comment]
I am not using a where object in the query, It is simply a field count issue that causes the query to be so large.  My environment is Django 1.10 and Django-salesforce 0.6.9.  I would like to help out on the "restricted by values(fields) or values_list(fields) query sets" as this is a blocker for me.  Is there an issue for this?

**Comment by hynekcer** [comment]
It is nice of you that you would like to help with testing.

A few tips: You can have two models for Account in two different models.py. E.g. a smaller Account for the most of code and an AccountFull that needs some restriction by values or values_list. The smaller model can be combined from the full model and a list of field names of a list of regular expressions for matching field names. You can find more information in my Wiki https://github.com/hynekcer/django-salesforce/wiki/Dynamic-fields (all common pages are automatically shared with the origin/master repository, but two new pages are only in my github) It exists still in the stable code 0.6.9 and I would appreciate a feedback.

I created a branch "bryancolligan" with a hack for you, improvement by 25% for your case, very similar to v0.6.9 (only 2 lines added today). It should be better for production, in the contrary to the current state of dev-07. It could be proved that the hack is correct and can never fail, but it looks nasty for me. I remove it soon.

**Comment by philchristensen** [comment]
I don't think it matters if you have a WHERE clause or not. IIRC we send the entire query as a GET request, and because of the way Django works, it has to list the fields in the SELECT clause instead of using a *

-Phil
sent from my phone

**Comment by hynekcer** [comment]
Much bigger queries are supported now up to 100000 characters, instead of 16k.

The size is now limited by this: `SalesforceError: MALFORMED_QUERY`  
`SOQL statements can not be longer than 100000 characters`
