### ISSUE TITLE
Sandbox gives internal server error, while Production works fine?

### ISSUE THREAD

**Issue by brighters** [django-salesforce/django-salesforce#169]
I have integrated successfully with our Production Salesforce instance, but switching to our Sandbox (https://cs86.salesforce.com) always gives an error. We actually have two sandboxes, and this error occurs exactly the same on both sandboxes. To date I have only been prototyping but am now using for real in a project and can't be creating test data in our production instance.

_"An internal server error has occurred"_

_"An error has occurred while processing your request. The salesforce.com support team has been notified of the problem."_

This is the settings config i'm using (with secrets / keys / passwords removed):

```
    'salesforce': {
        'ENGINE': 'salesforce.backend',
        'CONSUMER_KEY': "",
        'CONSUMER_SECRET': "",
        'USER': "hello@brightnetwork.co.uk.dev",
        'PASSWORD': "",
        'HOST': "https://test.salesforce.com",
    }
```

(The security token is appended to the password)

I wondered if you had seen this with Salesforce sandboxes before and could shed any light on the root cause please?

**Comment by chromakey** [comment]
Are you using the correct username for the sandbox?  When I work with my sandboxes, I have to append the sandbox ID to the end of the username.  i.e. user@email.com.20161004 (where 20161004 is the sandbox name)

**Comment by brighters** [comment]
Thanks for the quick response. Yes we're appending .dev and .test on the username, which is what we use to login without any issue.

**Comment by chromakey** [comment]
Nothing immediately jumps to mind.  Maybe try setting up a logger in your salesforce sandbox and see if salesforce is reporting something that might be of use?

**Comment by hynekcer** [comment]
Is the error message from login server or from the worker instance?
If you did not synchronized the sandbox after configuring the API access, you may to need to do it and modify CONSUMER_KEY and CONSUMER_SECRET accordingly. The easiest is to create a fresh sandbox from the working production instance (in order to narrow the number of unknowns) and to change only the username and security token. Maybe you get it on another instance to be sure. I expect that you use a standard instance name, not a "somethingcool.my.salesforce.com" what is not tested.

My experience is that Salesforce reports sometimes a very general and useless information in a case of security related problem like an invalid login - maybe to confuse the enemy?

Sandboxes are very well supported. (I have an interesting information that in the code for the version 0.7 being prepared, it will be possible to configure all different parameters for sandbox directly in a sub-key TEST of DATABASES['salesforce'] and automatically to switch to run tests on a sandbox, or to have two sandboxes - one with some manually created data and other very empty for automatic tests.) So it is strange that you have a problem with a simple sandbox.

**Comment by brighters** [comment]
Thanks for your help.

I'm not sure what you mean by login server or from the worker instance? The command I'd running to generate this error in the django shell is (params omitted for brevity):

`Account.objects.create(params)`

Ok yes I haven't synced since creating the API access - will try that to minimise the unknowns.

(Both our sandboxes are cs86 subdomains which are generated by Salesforce but I can point django-salesforce at test.salesforce.com or cs86.salesforce.com and I get the same error so don't think it's that.)

**Comment by hynekcer** [comment]
You have a traceback and the exact error message. You should see in the log / on the screen login requests and login success or fail. (I recommend to send by http://dpaste.com/ and put a link. I will copy the relevant info and the rest is removed after the period that you select) If you see there a `salesforce/auth.py` it is a login to "test.salesforce.com" if you see `salesforce/backend/driver.py` it is in a request for data to "cs86" instance.

Though the setting SF_LAZY_CONNECT=True is very good in many situations, especially on servers, if you report only one line from your code (not known if in manage.py shell or test or runserver?), you should to set explicite SF_LAZY_CONNECT=False - or you should to send enough information as is usual.

The best to find a problem is to go by small steps:

    $ python manage.py shell
    >>> from django.db import connections
    >>> cursor = connections['salesforce'].cursor()   # login now if not connected yet (if lazy connect is set)
    >>> cursor.execute("select id from account limit 1")
    >>> cursor.fetchall()

(You could have an Apex trigger for Account before/after Insert etc. The problem could be finally on your side. We should eliminate it starting by simple steps)

**Comment by brighters** [comment]
Thanks - waiting on re-sync of our .dev and .test sandboxes. 

This is the trace from your suggested steps above: http://dpaste.com/34GN62X trying to connect to https://test.salesforce.com - it seems to fail on oauth.

**Comment by hynekcer** [comment]
OK. This is probably the [problem TLS 1.1+ on Salesforce](http://salesforce.stackexchange.com/questions/139879): Production instance can work with TLS 1.0 (until spring 2017) but the sandbox requires TLS 1.1+. You should upgrade Python to 2.7.9+ or 3.4+ or upgrade your SSL libs.

(Tracebacks are very useful, but should not remain, because Google can't find a relevant text if so many similar noise remain on internet.)

**Comment by brighters** [comment]
This is my django shell
```
>>> import sys
>>> print (sys.version)
2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```
Do you still think it's TLS and worth upgrading that?

**Comment by hynekcer** [comment]
Also run `$  openssl s_client -connect test.salesforce.com:443` and look for a line `Protocol  : TLSv1.1` or higher.

**Comment by brighters** [comment]
```
SSL-Session:
Protocol  : TLSv1
```

**Comment by hynekcer** [comment]
Solved. You can upgrade or run a VirtualBox with a new system. Maybe there is still a setting that can downgrade the required SSL version on sandbox, but I would not recommend it. Spring is near.

I added this case to [Q/A to Error messages on our wiki](https://github.com/django-salesforce/django-salesforce/wiki/Error-messages).

**Comment by brighters** [comment]
One last question if that's ok please?

I upgraded (was a pain but managed it) and now:

```
openssl s_client -connect test.salesforce.com:443
Protocol  : TLSv1.2
```

But still the same error in django shell? What am I missing?

**Comment by brighters** [comment]
Resolved. Upgraded my python to use openssl latest version. Thanks again for all your help.
