### ISSUE TITLE
app_label logic in prep_for_deserialize reversed?

### ISSUE THREAD

**Issue by aventurella** [django-salesforce/django-salesforce#171]
https://github.com/django-salesforce/django-salesforce/blob/master/salesforce/backend/query.py#L147-L150

```
mod = model.__module__.split('.')
if(mod[-1] == 'models'):
    app_label = mod[-2]
elif(hasattr(model._meta, 'app_label')):
    app_label = getattr(model._meta, 'app_label')
```

If the user has specified `app_label` in the meta shouldn't that take precedence over the module path?

**Comment by hynekcer** [comment]
You are right. How did you found it? A failed get_model method? Do you know a *useful* simplified example? I think that it will be used in a broader test.

I have never thought that the app_label is too important for django-salesforce, except that it must exist, because SFDC doesn't add the app name to the table name. If you use a Model with the same name in two app, it is possible though both models share the same table.

Models in django-salesforce are not authoritative for database structure, also because objects and fields are frequently locked in Salesforce by dependencies of Apex classes. I frequently use inspectdb and I'm preparing [dynamic fields](https://github.com/hynekcer/django-salesforce/wiki/Dynamic-fields). That is fields and models refreshed by inspectdb to some helper model and filtered by a custom condition to a current model or to models in more apps. That do you think about? The best code for it is in [this my branch](https://github.com/hynekcer/django-salesforce/tree/fix167) When I switch between production and sandbox I easily refresh the helper model.py and I have never a problem now that some field (used in model, but not used by app) was not found. It helps also that I don't have a problem that some field, that is not present in all instances, can not be used because it is not in the app model. If I develop in the console, I frequently use directly the full helper model obtained by inspectdb.

**Comment by aventurella** [comment]
I have a django app that has 2 different regional deployments. One uses salesforce in the United States, the other does not.  Because sometimes it's not used and when it is used it's only a few API calls that I need, and because I was initially using another salesforce lib, until I found your fantastic work, the way I structured the folders was as follows:

```
client_name/
├── api/
│   ├── services/
│   │   ├── salesforce/
│   │   │   ├── actions/
│   │   │   ├── tests/
│   │   │   ├── apps.py
│   │   │   ├── models.py
```

Since the my initial salesforce implementation wasn't a "app" just effectively my driver, it didn't really  need to live in a more app appropriate location.  Also I have a 3-4 more services that break out similarly and now all live in the `services/` directory so it's easy to keep track them:

```
client_name/
├── api/
│   ├── services/
│   │   ├── salesforce/
│   │   ├── identity/
│   │   ├── message/
│   │   ├── blog/
```

All of these services are not driven by a "local" database, so it made sense to keep them together. 

As you can see the problem with the `app_label` logic as it stands would see `models.py` in `salesforce/` and assume the app name is `salesforce`. It's problematic as `django-salesforce`'s `app_label` is also `salesforce`.  Because it was not a django app originally there was no harm in naming my subfolder `salesforce`. Once I switched to use `django-salesforce` that would have had to change since but it never crossed my mind again until I discovered this issue.

The error that prompted me to begin stepping through the source was this:

`DeserializationError: Invalid model identifier: 'salesforce.Lead'`

Once I got though Django's ORM internals and landed in `django-salesforce` I found those lines above and thought: Why would the module path override the user's explicit choice? I better go ask.

My workaround, once I saw what the code was doing was just to rename my `models.py` to `sf_models.py` which forces it to use `app_label`.




As for a simplified test, I think you have the setup already:

https://github.com/django-salesforce/django-salesforce/tree/master/tests

Those tests do what you'd need to do, they bootstrap a `settings.py` file with an installed app from it's own directorty:

https://github.com/django-salesforce/django-salesforce/blob/master/tests/test_compatibility/settings.py

I think all that would need to happen is copy one of those:

```
from salesforce.testrunner.settings import *  # NOQA
from salesforce.testrunner.settings import INSTALLED_APPS

INSTALLED_APPS = tuple(x for x in INSTALLED_APPS if x != 'salesforce.testrunner.example')
INSTALLED_APPS += ('tests.test_compatibility',)
SF_PK = 'Id'
```

but provide one extra folder of depth:

```
from salesforce.testrunner.settings import *  # NOQA
from salesforce.testrunner.settings import INSTALLED_APPS

INSTALLED_APPS = tuple(x for x in INSTALLED_APPS if x != 'salesforce.testrunner.example')
INSTALLED_APPS += ('tests.test_app_label.salesforce',)  # <---------
SF_PK = 'Id'
```

Then just toss a `models.py` into 

```
tests/
├── tests/
│   ├── test_app_label/
│   │   ├── salesforce/
│   │   │   ├── apps.py  (using the newer AppConfig subclass)
│   │   │   ├── models.py
```

https://docs.djangoproject.com/en/1.10/ref/applications/
(I think this is 1.7+)

**apps.py:**
```
from django.apps import AppConfig

class TestSalesForceConfig(AppConfig):
    name = "tests.test_app_label.salesforce'"
    label = "test_salesforce"
    verbose_name = "Test SalesForce"
```

Ensure that w/e model in there set `app_label` on it's Meta

```
from salesforce import models

class Lead(models.model):
    email = models.EmailField(blank=True, null=True)
    # ...

    class Meta(models.Model.Meta):
        db_table = 'Lead'
        verbose_name = 'Lead'
        verbose_name_plural = 'Leads'
        app_label = 'test_salesforce'
```

Then try to deserialize some data.

**Comment by hynekcer** [comment]
Shortly said, you use app config due to namespace problems. It is probably an important reason why  app config exists. The standard naming is probably very good in a new project started at greenfield.

---
The directory "salesforce/testrunner" is a demo and test project used in relative normal tests "salesforce/tests". I don't like the directory "tests" too much. It contain some important special tests that need one ore two modified settings and the a big part is usually inherited from "salesforce.testrunner". It iseasier for maintenance than a big copy/paste, but it is little confused if a code must be debugged and the source path is very different from import path not easy to remember.

"fantastic work"? It could be if it it won't be a spare time project. I have an idea of SQL to SOQL translator project, that that could be useful also for SQL Alchemy and for frameworks in other languages like .NET, that could probably be easier to get some funding.

Yes, the package name "salesforce" is great; on the other hand it is a challenge for me to improve some features so that other packages with the same namespace are not necessary in a normal project. Currently I'm implementing bulk operations. (it's sleeping due to small details, like bulk inserts are not good implemented in Django < 1.10. Should I add a new API function now or wait for a clear one?)

**Comment by hynekcer** [comment]
Thanks for the fix and the test code.

Excuse that I forgot to solve the essence of your problem, probably because you didn't write an error message here explicitly. (exception FieldDoesNotExist due to KeyError in `self.fields_map[field_name]` in Django) I didn't realized how it was serious and I wrote a not important that more app models can use the same Salesforce table and use different subsets of fields. Yes, but I didn't know that the used models were crossed due to app_label.

**Comment by hynekcer** [comment]
You inspired me that 'salesforce' is not necessary in INSTALLED_APPS, see [384d2da](https://github.com/django-salesforce/django-salesforce/pull/196/commits/384d2da95b62ca0dcfd9f4e9e0690548021e39d3). It is probably still better not to use that free name for other apps.
