### ISSUE TITLE
HttpsReadTimeOutError

### ISSUE THREAD

**Issue by uditagarwal** [django-salesforce/django-salesforce#174]
Thanks for this extremely useful plugin. It's working well for me.

However, I see a bit of an issue. If I use the plugin after about 12 hours, my first call to the SalesForce API to create a new entry always fails because of a TimeOut error. Subsequent requests pass without an issue, its just the first request after a long time that causes it to error.

Is there a way I can solve this?

**Comment by hynekcer** [comment]
Yes, it is solved in some my old development branch. I will look at it and commit later. (busy)

**Comment by hynekcer** [comment]
I remember, that a temporary solution before the fix was to run a cron job with a request every 119 minutes or more trequently.

My new solution uses a smart session and authentication management that prevents many similarly unfrequent problems, usual at client software for network services. Expect a beta quality code that could be worse eventually in some area until it is tested intensively, e.g. also by you. Don't expect anything before a month later, please.

**Comment by uditagarwal** [comment]
Hey!

Thanks a lot for your response. Can you please link to the development branch so that I can see if i can use it on my project whenever you find the time?

I'll wait for your solution!

**Comment by hynekcer** [comment]
It is  
`pip install -e git+https://github.com/hynekcer/django-salesforce.git@b92c5f2c2c97b3434d554fd5a90aaa5a4ce9134b#egg=django-salesforce`
(I refer to a fixed commit head because my development branch can be heavily rewritten whenever I write many fixing commits for a code that is still in the development branch and I move these commits to the right places and squash together.)

One important fix is "Timeout as tuple" (shorter for connect, longer for queries - data)

    SALESFORCE_QUERY_TIMEOUT = (4, 15)  # default (connect timeout, data timeout)

Other important fix is "Prevention SF account locking" if you e.g. must change a password and there are many requests accidentally before the password can be changed also on web server. Excessive number of failed login requests is banned by SF even if you don't specify a maximal number of allowed failed login.

Useful info about the branch is in a recent issue #173.

**Comment by hynekcer** [comment]
This issue is rather improved ty timeout as tuple (a commit in #185). It requires requests 2.4 or higher.

A possible timeout, after the connection was inactive longer than 120 minutes, but the closing packet from SF was lost for some reason and the local part of the connection is still supposedly open, is still not solved. (It depends on big refactoring that can not be committed to master yet. This issue remains open.)

**Comment by hynekcer** [comment]
Fixed

* Added: command ping_connection that automatic called after every
longer inactivity to minimize timeouts. Fixed #174 (92fb900, 0117367)

The probability of timeout increases by the previous inactivity, if we consider a possibility of incorrectly closed connection e.g. by a lost reset packet from Salesforce.

After an inactivity longer than 300 seconds will be send an unimportant REST request with a very short timeout before the next request. If the connection lives (more probable) than it takes about 0.05, if it is dead then it takes about 1.2 sec. Both variants are much shorter than a long timeout.
