### ISSUE TITLE
SysCallErrorOpenSSL.SSL in _raise_ssl_error (104, 'ECONNRESET')

### ISSUE THREAD

**Issue by flash286** [django-salesforce/django-salesforce#180]
Sometimes I'm getting very strange error. As i can see, it's not related with any place in code or values in model.

```
File "common/services/product_manager/__init__.py", line 87, in get_programs_by_store
    account = Account.objects.filter(vitagene_id=store.sf_id, is_deleted=False).first()
  File "django/db/models/query.py", line 550, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "salesforce/backend/query.py", line 241, in iterator
    cursor.execute(sql, params)
  File "salesforce/backend/query.py", line 421, in execute
    response = self.execute_select(q, args)
  File "salesforce/backend/query.py", line 477, in execute_select
    return handle_api_exceptions(url, self.session.get, _cursor=self)
  File "salesforce/backend/driver.py", line 143, in handle_api_exceptions
    response = f(url, *args, **kwargs_in)
  File "requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 370, in send
    timeout=timeout
  File "requests/packages/urllib3/connectionpool.py", line 533, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "requests/packages/urllib3/connectionpool.py", line 239, in _get_conn
    conn.close()
  File "python2.7/httplib.py", line 815, in close
    self.sock.close()   # close it manually... there may be other refs
  File "requests/packages/urllib3/contrib/pyopenssl.py", line 213, in close
    return self.connection.shutdown()
  File "OpenSSL/SSL.py", line 1522, in shutdown
    self._raise_ssl_error(self._ssl, result)
  File "OpenSSL/SSL.py", line 1178, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
```

Django: 1.9.11
Python: 2.7.6
django-salesforce: 0.6.9
backports.ssl: 0.0.6

**Comment by hynekcer** [comment]
Do you use TLS 1.1? (or any better)

Python versions supported by Salesforce (SFDC) are Python 2.7.9+ and 3.4 because TLS 1.1+ is required. See the README here (and thanks for version info, that the cause seems clear.) It is even easy to create a virtual environment with downloaded newer Python or other Python installed by Anaconda or compiled from source.

It is strange that you get the error only sometimes. I have no experience with backports.ssl. It seems that it is not supported good by `requests` package. You see that is an error in connection.close and connection.shutdown.

(It is still possible to leave old insecure protocols enabled on Salesforce setup, but not recommended and you will probably get warnigs every week that some old clients are still connecting and old protocols will be turn off soon without any possible workaround.)

Maybe an additional exception can be caught silently (if you can monitor the traffic at the time of error like lost packets, reset packets, timeout etc. and provide really many information) The problem is to decide correctly that the request should be retried. (It is not easy, because sometimes more issues are possible due to auto-repeat than by raising exception. If an error of the same type can be very frequent, then it is possible the account or IP address will be banned temporarily by SFDC after many ignored errors.) We use a variable settings.REQUESTS_MAX_RETRIES and requests are retried only by `requests` logic after timeout. It would require more investigation from you and finally it will be probably an issue for another package.

I think that we should not treat specific exceptions from optional packages if they are uncaught by urllib3 and requests and the nearest exception in the hierarchy is a generic `Exception`.

**Comment by flash286** [comment]
@hynekcer Thank you for a very useful answer. First i would try to update python version to 2.7.11

**Comment by flash286** [comment]
@hynekcer Yes, i update python version, and during the week, i was not received any errors. You may close the issue.

**Comment by philchristensen** [comment]
@flash286 Thanks for the report. It's useful having details of the symptoms since more and more people are going to start running into this.
