### ISSUE TITLE
Best way to run in environments without connectivity to Salesforce API?

### ISSUE THREAD

**Issue by andrewglancy** [django-salesforce/django-salesforce#190]
This plugin is working great for us and we have an inquiry/documentation request. 

**Question:** What is the best way to run a django server that includes django-salesforce and no available Salesforce instance?

**Background:** We've been exploring is running our apps for development and CI/CD purposes when there is either no access to a Salesforce API or even no access to internet entirely (no active network interfaces except localhost). The dream is that we can run our apps and continue developing in these rare case we have no internet - like on a beach somewhere remote or on an airplane without internet on the way to getting to that beach.

**Possible Solutions?:** My understanding is that one option is to point to a local instance of SQLlite. Another option we've looked into is disabling the System Check Framework for the app where we use django-salesforce.

Currently if we disconnect from the internet and try to run our apps we get stuck with 'Performing system checks...' How do we move beyond this issue?

**Comment by hynekcer** [comment]
You see some information in [README - Advanced usage](https://github.com/django-salesforce/django-salesforce#user-content-advanced-usage) - Testing: Use `SALESFORCE_DB_ALIAS='default'` or a new normal database that doesn't require SFDC. It is better than to invent a new mock object. Did you tried it?

**Comment by hynekcer** [comment]
Some your integration tests could probably require SFDC unavoidable, but you can mark them to be skipped in offline tests by `@skipUnless(default_is_sf, "Default database should be any Salesforce.")` similarly as I do it sometimes with test_integration.py to verify that even some simple tests of django-salesforce can pass with SALESFORCE_DB_ALIAS='default'.

What is probably not for you: I wrote a MockTestCase class (last year on holidays started with a similar motivation :-), with record and playback and online modes, to make possible some offline tests that heavily depend on SFDC API where SQLite is not enough (like convert Lead to Contact) that should replay the responses if the sequence of all requests equals exactly to some recorded and. It requires at least a slow occasional mobile connection and it is not committed to GitHub yet because only a rudimentary part is ready that was useful for me.

**Comment by leilabl** [comment]
@hynekcer Thanks for your response. I work with @andrewglancy, and we tried setting `SALESFORCE_DB_ALIAS='someothernames'` among other tweaks.

We currently have the following setting for trying to run the salesforce db locally when there is no internet connectivity or for tests:
```
'salesforce': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'salesforce',
}
SALESFORCE_DB_ALIAS = 'salesforce'
DATABASE_ROUTERS = [
        'salesforce.router.ModelRouter'
]
```

What is interesting is that when we run `makemigrations` and `migrate` the sqlite database gets created but the actual tables are created in our default database instead of sqlite. When we hit the views that call the Salesforce models, Django tries to access sqlite and does not find the tables, throwing the following exception:

Request Method: GET
Request URL: http://localhost:1000/my-view/
Django Version: 1.10
Exception Type: OperationalError
Exception Value: no such table: SalesforceTable__c
Exception Location: /my-project-directory/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py in execute, line 337
Python Executable: /my-project-directory/env/bin/python
Python Version: 3.6.0

Please let us know if you have ideas for what may be missing so that the migrations create the tables in the correct database.

Thank you!

**Comment by hynekcer** [comment]
You can try to create salesforce tables in the alternate database this way

    python manage.py migrate --database=salesforce

 (I'm busy, not verified now.)

Maybe I can fix `ModelRouter.allow_migrate` later after careful consideration not to break current use cases.

**Comment by hynekcer** [comment]
You can use a new patch #191 or you can select individually which Salesforce tables should be created where by explicit migrate.

    python manage.py migrate --database=salesforce your_salesforce_apps...

Or you can use a patch #191

Both solutions works perfectly and it is verified that all commands `makemigrations`, `migrate`, `test` and `shell` can work without any network access. (works with all supported Django versions including 1.11)

explained from README: It is necessary to write an explicit `db_table` attribute if you run SalesforceModel on a normal database, (because migrate command would create them with "appname_" prefix otherwise which you probably don't want):

    class MyModel(salesforce.models.Model):
        ...
        class Meta:
            db_table = 'MyModel__c'
