### ISSUE TITLE
[Django 1.11] Error on bulk_create

### ISSUE THREAD

**Issue by dhbahr** [django-salesforce/django-salesforce#193]
I'm using accounts with different record types, and if I save new accounts one-by-one all works good, but if I try to use `Accounts.objects.bulk_create([acc1, acc2, ... accN])` I get `'RecordType' object has no attribute 'record_type_id'`.
Is there a way to solve this or is it a known limitation not planned to support in the short run?
Best regards and thanks for your great work!

**Comment by philchristensen** [comment]
There maybe some development branches around different ideas, but at this time there's no specific plans to support bulk create. If you really need bulk create you maybe better off leveraging the SFDC Bulk API: 

https://developer.salesforce.com/page/Bulk_API

**Comment by dhbahr** [comment]
Yes, it was my original idea, just trying not to mix it up if not needed... thanks for your reply, you can close this one.

Happy hacking!

**Comment by hynekcer** [comment]
I can't reproduce your problem on [my test case](https://gist.github.com/hynekcer/22c5d9736b27aaa500e4f298f5ec3425) (mix of 200 Contacts of 3 record types. I saved my negligible example externally, because I want delete is soon.)

Please write your simplified test case to demonstrate the problem.

**Comment by hynekcer** [comment]
The method **"bulk_create" is supported since v0.6.9**. It works much faster if also "beatbox" package is installed. I contributed to two beatbox repositories to support Python 3.4+ and 2.7, but currently I don't want to maintain beatbox (I got that offer) and I use my beatbox fork [git+https://github.com/hynekcer/beatbox-davisagli.git@7f628a789cba#egg=beatbox](https://github.com/hynekcer/beatbox-davisagli/tree/python3)

 (I'm going to support also bulk delete soon.)

**Comment by dhbahr** [comment]
interesting .. I'm reopening this then, bit late now, but tomorrow will provide the sample code. Looking forward, thanks @hynekcer !

**Comment by hynekcer** [comment]
FYI: added support for setting primary keys on objects created using bulk_create() by PR #194 (together with other changes) [similar to Postgres bulk_create](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#bulk-create).

**Comment by dhbahr** [comment]
Heh .. sorry for all the fuss, turns out it was a dumb mistake on my part.. got it running now and works just fine!!
Thanks again, @hynekcer!

Ps. I have a followup (mere curiosity): is the bulk_create using the REST api or does it use the BULK one?

**Comment by hynekcer** [comment]
Nice short question. Nope :-) I optimized it for medium size fast requests divided into chunks by 200 objects. I prefer SOAP API if `beatbox` is installed. The speed is around 200 objects per second and it is probably faster than BULK, up to about thousand objects. Bulk would be generally too slow for a web server or it would be unpredictable due to low priority. If about 10000 objects are inserted by SOAP I feel some slow down because I guess SFDC dislikes high average load on normal priority requests. It is still a good compromise for me also for data migration (in python shell or jupyter notebook). SOAP consumes one API call per 200 objects in governor limits statistics.

If beatbox is not installed, `composite batch` REST requests are used by 20 objects. I implemented it when batch was a pilot project without enough documentation. It is four times faster than individual insert, but was is a bad idea because it only encapsulates any independent requests and it uses one bid normal request splitted 20 to internal fast requests on SFDC, accounted as 21 API calls. It could be possible to use currently a Composite SObject Tree REST API request by 200 objects, probably similarly efficient to SOAP, but I'm not interested more after implementing SOAP.

If one row is inserted (by normal "save()" or by "bulk_create([one_ object])") a normal REST API is called.

(Django bulk_create converts the data to a list of ORM objects internally. Memory requirements could be a bottleneck for extra huge cases that really require bulk api.)
