### ISSUE TITLE
104 ConnectionResetError

### ISSUE THREAD

**Issue by lanterno** [django-salesforce/django-salesforce#200]
Hi guys,
I've been facing a random error message that I can't get my had around. The weird thing is that I haven't found anyone who faced a similar issue before, and I can't even find a way to regenerate it myself.

So the error is simply as I typed in the title. I get very random 104 ConnectionResetError errors every now and then. It happens randomly, and on any endpoint I use.
I can't really provide code from the project, because I wouldn't know which part to share exactly.
I think this is either something related to the connection itself "On the network level, maybe!", or maybe salesforce just drops connections for some unknown reason?! 
I tried to analyze the time patterns, because maybe this happens on certain time intervals, but we're still in development, so not much data to base a conclusion on.
Another solution tried was a simple try/except, to resend the request, but the second one failed too which was weird. I think delaying the second by a couple might work, but I haven't tried that out yet.

so anyway, my question is, Did someone face this same error, and/or know of a solution?

**Comment by hynekcer** [comment]
I found a strange commit with ConnectionResetError in the [pull request 192](https://github.com/django-salesforce/django-salesforce/pull/192/commits/1314858c2fb55545c35673ff69ba7199d2a7c70a) in April. Now I understand what you tried.

I have found some links. It is not very optimistic, but inspirative.  
https://salesforce.stackexchange.com/questions/107673/connection-reset-exception-using-soap-integration
https://developer.salesforce.com/forums/?id=906F00000008pMeIAI

You need to investigate it more.
+ Is it a problem with login.saleforce.com (test.salesforce.com) or with salesforce data instance?
+ Do you monitor number of new connections to SFDC per minute? Number of parallel connections? Number of connections in a state before a complete close, not state ESTABLISHED? Do you develop on Linux?
+ Do you use also SOAP frequently immediately before the problem? (If I remember, it creates and closes a connection for every request)
+ I think that this error can be reproduced if a connection is created, pull out Ethernet, kill the process to break the connection on the local side, plug Ethernet and repeat it more times. Then would be understandable that SFDC starts to reset new connections and that retry doesn't help.
+ Every SFDC instance has about three IP addresses. It is not easy to convincingly demonstrate that another tool can connect to the same IP address from the same IP address or also by the same session, without extensive monitoring of IP or logging. E. g. Wireshark is perfect at own organization, but with risk of leak some sensitive private data outside. I can not help until you analyze your data enough.

**Comment by zee93** [comment]
I asked around, and apparently this happened with other people too, but I haven't found direct reasons/solutions for it yet! I got a suggestion to change my hosting though which I thought kinda weird, but maybe I'll try it out since it's a network error after all.

My main problem really is putting the salesforce interactions in my main request/response flow. It would be better to separate the salesforce interactions in a scheduling tool like celery and implement a retry mechanism into it. That probably should be followed for all similar workflows, right?
Anyway, that doesn't really solve the issue, so I'll keep digging.

To answer your questions above, 
- this problem happens randomly with both login.salesforce.com and test.salesforce.com, but I'm not sure what is a `salesforce data instance`.
- I develop on Ubuntu. But I mainly use Docker for both local and production environments. I don't have monitoring installed yet! I only use Sentry for error monitoring. I was thinking of add Opbeat for my metrics. Do you have a preferred tool?
- Not at all. It happens most of the time with regular REST calls. The only SOAP call I use is the convertLead and I rarely use it.

**Comment by hynekcer** [comment]
Data instances are e.g. na1,salesforce.com, ap*.salesforce.com, eu*.salesforce.com or cs*.salesforce.com or what you see after login in the browser. Login servers are login.salesforce.com or test.salesforce.com. You can see it in the traceback that `...site-packages/salesforce/auth.py` is present (login request failed) or not (data request). A statistics of connections can be found by `netstat -t | grep salesforce.com` and counted ESTABILISED, *_WAIT and other status, especially connections to the site that rejected a connection. If the source IP ports are frequently changing then you can guess from outside how frequently are new connections open.

**Brainstorming opinions**  
Maybe you start too many connections by many processes or kill and start a new process too frequently. Every login is by default logged on the terminal. You can easily configure a format with timestamps and log it very simple how you need. Maybe you are running a multi-tenant application... (It is said that it works also well with django-salesforce, but I don't know details.)

Maybe you find something unexpected high on Setup / Security Controls / Session Management log or Login History. Four logins per minute are absolutely fine over a very long period if the old connections are closed correctly. (Not tested more frequently.)

I think that Celery is a last resort or a temporary solution or useful for investigation. I would try first to specify [Forcing Python Requests to connect to a specific IP address](http://www.tomechangosubanana.com/2017/forcing-python-requests-to-connect-to-a-specific-ip-address/) on retry after remote reset. You can also try another tool to connect and check if the success difference is statistically very significant, but I think that a web browser retries another IP addresses returned by DNS and this is why it is more successful. I think that requests package is originally written for web servers but not optimized by default to reach higher reliability on cloud services. (to can switch IP before an overloaded IP is removed from DNS. What is universally better? To can not connect rarely or to see possibly rather obsoleted data at that time?

I expect that to retry regularly after reset by SFDC will make it worse. Better is to think what he does not like about me. Maybe Docker or some firewall or NAT before development machine or something that terminates an unused connection silently sooner than python-requests or Salesforce. Maybe Salesforce thinks about me I'm holding to many connections, but I think they have been lost yet and I must open a new. It can be useful to close an unused connection e.g. after two or five minutes by python-requests pool. I remember a bad experience many years ago when I was working on Windows with Linux VirtualBox. (Iddle timeout or keepalive or what it was? Now with native Linux nothing need to be configured and I can rely on connection status.)

You need to log some statistics data about the traffic before the TCP reset error. Or can write a standalone application (like a new command for manage.py) that regularly runs a request e.g. for 8 hours with some frequency and then 2 hours pause (in order to be sure SFDC closed all lost connections) and repeat with another frequency. Maybe you find that a request more frequently than 2 minutes is perfect, but e.g. 6 minutes could be the biggest problem and think that some delay can accumulate lost connections on SFDC most frequently. Then unused connections must be closed at better timeout or configured a better keepalive packet interval. If you find a solution by python-requests, e.g. by a custom [Transport Adapter](http://docs.python-requests.org/en/master/user/advanced/#transport-adapters) I can add a hook for customization.

Please don't denounce what is incorrect too soon. Try to find a way. I'm preferring to delete the brainstorming altogether after you find a mistake.

**Comment by hynekcer** [comment]
I think that the best method (to can do it yourself) is to try to change everything first the simplest way. Create a new developer SFDC account independent on your company. Install django-salesforce at home (where are no other connections to SFDC) on anything you have (windows, mac or linux) without any containers etc. and try the test with periodic requests. I believe that it will work. Then make slowly these two test environments more and more similar, preferably to continue at work, until you find an important difference. Maybe a row in container configuration finally.

By "monitoring" I meant something very simple ad hoc used probably only once to see inside and not important later more.

salesforce.backend.query.request_count or in future salesforce.dbapi.driver.request_count

**Comment by zee93** [comment]
Ok. Thanks Hynek for all the help and ideas. I like the idea of starting simple and small and rise up from there until I find the single change that causes the problem. It's only problem is how much time it needs, so I'll have to do that and at the same time have a workaround in place. 
Will update the issue with my findings and/or workaround.

**Comment by hynekcer** [comment]
It will be not very complicated probably. You can try also the reverse direction: On the same hardware to simulate a similar traffic intensity to a sandbox and to change to the simple variant unit you match. Create new sandboxes until you have two sandboxes at the same site.

You can target at
A) an **attribute** of the request, that is temporarily **blacklisted** or problematic: Your IP address, your account, your session token, all 3 IP addresses of SFDC instance or only one. How long inactivity is usually necessary until it starts to work. (e.g. until DNS cache expires and the app starts to use another IP?) Are retries contra productive?

B) Guess the most probable **reason**:
* many deterministically broken connection - e.g. after inactivity longer than something - use the default `REQUESTS_MAX_RETRIES=1` in the test app to see them.
* probably high traffic at SFDC - coincidence of similar problems at the same time at absolutely unlike independent requests.
* after your high continuous traffic from more connections or after many consecutive invalid requests. (but you would see normal verbose exceptions first in both cases)

**Comment by hynekcer** [comment]
Closed, because there is not enough information for long time to reproduce the issue. Can be reopened if more information are known.

Discussion forums say mostly that ConnectionResetError is the most probably a problem on SFDC side.
