### ISSUE TITLE
Locale influencing the 'If-Unmodifed-Since' header

### ISSUE THREAD

**Issue by dhbahr** [django-salesforce/django-salesforce#210]
Hey guys, I have been experiencing the following bug: 
When the locale is not English, the value of the 'If-Unmodified-Since' header is being generated in that other locale, causing Salesforce to refuse the request.

SEE: https://github.com/django-salesforce/django-salesforce/blob/master/salesforce/backend/query.py#L598

I have added some workaround to set always the locale to 'C' when this is executed and then restoring the old one back. I was wondering if this is something you would be interested to fix upstream.

Best

**Comment by hynekcer** [comment]
I see that we must use the builtin `email.utils.formatdate` for RFC 2822 datetime string. It uses hard coded names Mon, Tue... Jan, Feb... I did not like that, but is is really a better solution than to want to depend only on datetime modules.

**Comment by hynekcer** [comment]
The code "If-Modified-Since" was originally due to the upstream bug in Salesforce [Composite Batch API PATCH call returns "entity failed If-Unmodified-Since test on update"...](https://success.salesforce.com/issues_view?id=a1p300000008aYNAAY&title=composite-batch-api-patch-call-returns-entity-failed-if-unmodified-since-test-on-update-but-no-if-unmodified-since-header-in-the-request). It is now obsoleted and removed because the original required header is now completely ignored.

I recommend to install Beatbox (currently not the version from PyPI) that is automatically used by django-salesforce if present. It is useful if you need higher speed-up or you are motivated by governor limits. The old composite/batch call concentrates many calls to one network request, but they are executed and committed individually again on the Salesforce side. I didn't try to modernize it to other type of composite request because I prefer to install Beatbox.
