### ISSUE TITLE
Using Salesforce as an OAuth identity provider

### ISSUE THREAD

**Issue by KernelPan1k** [django-salesforce/django-salesforce#212]
Hello, I would like to know if it is possible with this module to authenticate with oauth to salesForce in order to give a private access to the website?

Thank you

**Comment by philchristensen** [comment]
Could  you elaborate a bit more? You can probably do what you want, but it might be overkill do use django-salesforce.

**Comment by KernelPan1k** [comment]
Thank you for your quick response, I will try to be more specific. 

I will soon develop a project with Django and this project will have to communicate with the Salesforces API. django-salesforce seems to be perfect for that. But in this project, I will also have to allow users in the Salesforce database to access a private part of the website. I want to know, if I can authenticate on the website a user present in the database of Salesforce using Oauth?

**Comment by philchristensen** [comment]
Ah, so you'd like to use Salesforce as an identity provider for your custom website. That's an interesting idea, but not a use case supported by django-salesforce. A cursory Google search suggests it's not too hard to achieve though; I think you'd want to leverage this project:

https://github.com/python-social-auth/social-app-django

It doesn't currently directly support Salesforce, but it supports other OAuth-based identity providers, so adding SFDC support shouldn't be too hard. If you'd like something more production-ready, you should be able to leverage Auth0 for the same purposes:

https://auth0.com/authenticate/django/salesforce

**Comment by KernelPan1k** [comment]
Thank you very much for your answer and your documentation links.

**Comment by philchristensen** [comment]
Oh awesome. I only did a cursory review of the docs.

**Comment by KernelPan1k** [comment]
@jacobwegner ok great, thanks i'm going to look at this

**Comment by l-kotzur** [comment]
Hey there, 

I wanted to add oauth via allauth:
https://django-allauth.readthedocs.io/en/latest/providers.html#salesforce

Nevertheless, there is a conflict by using allauth-salesforce and django-salesforce together:
`django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: salesforce`

Therefore, I deleted "salesforce" in the INSTALLED_APPS and cannot use anymore the `inspectdb --database=salesforce`. 

Would it be an idea, to call you app instead "django-salesforce"? I could then further use the full functionality of django-salesforce.

Best
Leander

**Comment by hynekcer** [comment]
It can be solved by small configuration module with a few lines that you write for django-salesforce or for django-allauth to solve the name conflict in Django registry. Read about [Configuring applications](https://docs.djangoproject.com/en/3.0/ref/applications/#configuring-applications) in Django docs. It should not be complicated

> To configure an application, subclass AppConfig and put the dotted path to that subclass in INSTALLED_APPS.

You probably need only to specify two attributes of that class

- `name` some different identifier, similar to 'salesforce' (underscore allowed, but not dash)
- `path` that depends on your decision which app you want to rename ('salesforce' or 'allauth.socialaccount.providers.salesforce'

I think that principally it is more a problem of django-allauth to recommend a solution, because they pollute a huge name space a and very probably many django applications of the same name exist for a service that they use a an OAuth2 provider. (e.g. django-disqus) I think that you find an issue or question/answer for another name name conflict. But I repeat, I think that the solution is easy, not longer than five lines of code. (import, class, name, path and maybe one that I forgot)

**Comment by hynekcer** [comment]
Tor example create the following file somewhere in your project, e.g. in 'my_sf_app.apps'
``` python
from django.apps import AppConfig

class SalesforceDb(AppConfig):
    name = 'salesforce'
    label = 'salesforce_db'
```
Write a string `'my_sf_app.apps.SalesforceDb'` into `INSTALLED_APPS` instead of `'salesforce'`

**Comment by philchristensen** [comment]
Agreed with @hynekcer that changing the app name not in the foreseeable future.

**Comment by hynekcer** [comment]
@l-kotzur The conflict of django-allauth against many packages is a frequent issue, not specific to Salesforce:  e.g.
[django-allauth issue 393](https://github.com/pennersr/django-allauth/issues/393)

Added note to wiki [Help for some Error Messages](https://github.com/django-salesforce/django-salesforce/wiki/Error-messages)

**Comment by l-kotzur** [comment]
@hynekcer Great support. It works like charm. I feel a bit ashamed that I have not done the research by myself.

And I agree, it should be solved by allauth.

**Comment by hynekcer** [comment]
@l-kotzur If you want to express your satisfaction with this framework, you can try a Sponsor button. A developer in my country could have been sponsored this way since the last week. I would appreciate your feedback also whether the form is friendly enough to you.
