### ISSUE TITLE
Helping with Django-Salesforce development

### ISSUE THREAD

**Issue by ndingdw** [django-salesforce/django-salesforce#221]
Hi guys!
 
We have been using your project in our Django App for more than two years and we are currently migrating our codebase to Python3.7 and Django2.2 LTS. Noticed that the current release doesn't support the values(), values_list(), defer(), only() and some raw() queries, we are wondering that could you give us the access of the development repository? And  we can help with the testing part!
 
Thank you!

**Comment by philchristensen** [comment]
I’m afraid don’t understand. This *is* the development repository and pull requests are encouraged.

Thanks for your support!

**Comment by nding1718** [comment]
Sorry I didn't make myself clear. I found this in the README: 
"Unsupported methods are currently: values(), values_list(), defer(), only() and some raw() queries. (All fixed in a development repository, waiting for review, consensus etc.)"
So the current repository we have and this fixed "development repository " are the same one?

Thank you.

**Comment by philchristensen** [comment]
I guess I’m not what other repository you’re referring to. This is the only repo there is or has ever been.

**Comment by nding1718** [comment]
OK, I see. really appreciate the quick response. Thank you very much!

**Comment by hynekcer** [comment]
Yes, I promised to release a new version by end of January. I'm working on a big refactoring and because I do it alone now I try to reorganize the last unpublished commit history finally to clean readable commits by "git rebase --interactive", you are right and maybe I commit all for the new version today here for testing.

I worked in 2016 on a similar big principal refactoring, but the difference was so big that it was not possible to merge or combine the branches. Every old idea was now assessed and implemented again or blind alleys were rejected. It cost a lot of time. I implemented some operations by SOAP API, where I even considered to accept reject to be maintainer of Beatbox package, because REST API did not support any for of fast operation on collection of objects. ([SObjects collections](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_sobjects_collections.htm) exist since Salesforce 42.0). I discovered a small security issue in some form in many mainstream databases by work on query compiler for django-salesforce, that I verified in C code in some of them and reported to these projects etc...

**Comment by nding1718** [comment]
That sounds great! And also where can we find the latest developing repository? Or do you have a task list? we can help with them!
Thank you!

**Comment by hynekcer** [comment]
All code is now in PR #222, still branch [cumulative-0.8](https://github.com/hynekcer/django-salesforce/tree/cumulative-0.8). The most important change in the history of the project has been successfully switched in the last two days. You would lost time a energy if I had published anything before this weekend. Everything important works now. No important to do list. Test it, what to fix before v 0.9.

It worked with Django 2.2-alpha from January 5, but the version from January 16 requires transactions. It will be the next version. You can try to find a way. It is really hard for the beginning of cooperation.

**Comment by philchristensen** [comment]
I’m glad to change to USE_TZ to True if that’s the best approach.

**Comment by nding1718** [comment]
OK, got it.  And thank you very much for the good work on this project!

**Comment by hynekcer** [comment]
@nding1718 A general testing by working on anything for you useful will be appreciated now.

Please, can you write a more complex test for DateTimeField for different use cases with time zones?

I can fix the problem or you can suggest a solution if you want, but my experience is that a good test case with more tests and more settings is an advantage to change anything with time zones wisely, especially if a new and an old behavior should be also compared. Also a short documentation can be useful? You can see that Django documentation contains a specific info about time zones and `USE_TZ` ` for [two database backends](https://docs.djangoproject.com/en/2.1/ref/databases/#s-time-zone-definitions). Maybe something for Salesforce is also necessary or useful. You can find that the previous solution that has been written in August 2013 without `django.utils.timezone` module, because the supported Django versions were 1.3, 1.4, 1.5 and the oldest Django without USE_TZ setting and without `django.utils.timezone`.

Tests:  
* Save a DateTimeField, read and compare.
* Save an object, read the last_modified_date, compare to the system time with -+15 minutes tolerance acceptable.
* Try to select an object with additional exact `.filter(last_modified_date=...)`

Everything with aware datetime objects and `USE_TZ=True` is easy. Naive localized date times with USE_TZ=False TIME_ZONE=myzone are probably useful on local machine in some easier development from command line, for some data sources and for easy conversion timestamp to date.

A recommended writable DateTimeField is Lead.EmailBouncedDate that is a part of example.models. (TODO comment write a test) You can use a decorator `@override_settings(USE_TZ=False')` to customize settings for a test.

(If someone is interested for a theme worth of an computer science thesis, I know some, but you wrote you prefer to use this tool only for your app.)

**Comment by hynekcer** [comment]
See "Unoffical support for Django 2.2 alpha 1" #225

**Comment by nding1718** [comment]
Thank you for the information, will work on this.

**Comment by stefanfoulis** [comment]
Looking at the mentioned PRs in this issue they all seem to be merged, I _think_ it could be closed. Correct?

**Comment by hynekcer** [comment]
@stefanfoulis  Thanks for feedback. There is still a marginal bug with timezones. Some short code should be removed if `USE_TZ=False` is really unsupported or that code should be fixed. That is the only reason why this remains open. I crossed out the reference at v0.9 PR 248, because because it will be postponed even after 1.0.

**Comment by hynekcer** [comment]
Fixed tests to not depend on `USE_TZ=True`.
