### ISSUE TITLE
Migration notes

### ISSUE THREAD

**Issue by dhbahr** [django-salesforce/django-salesforce#227]
@hynekcer, @philchristensen maybe it would make sense (if at all possible), to include on the release notes all (or at least noticeable) api changes? 
Like `backends.driver` has been moved to `dbapi.driver`, stuff like that so people updating from an existing 0.7.2 release knows what needs to be updated in their code?

**Comment by philchristensen** [comment]
It’s certainly a good idea, although breaking changes have been quite uncommon for some time, 0.8 being a notable exception.

I’m down to create some documentation to cover this, but I don’t think we have an easy way to know all the breaking changes other than through manual review. Any help in that would be appreciated.

**Comment by dhbahr** [comment]
I vow to report whatever I come across :D

**Comment by hynekcer** [comment]
I'm not aware of any change in API caused by moving a code, especially by moving to `salesforce/dbapi`. Maybe you need some undocumented code to be a part of API, then inform us what undocumented you used or you think that could be used by other people. I have fixed a typo now #228. (I will continue soon...)

**Comment by dhbahr** [comment]
Well .. thing is, at some point I was importing the  `handle_api_exceptions` method from `backend.driver`and that went away. At first I thought it had moved to the `dbapi` module, but there is nothing public there. I then realized that I actually was not really using the import at all (:disappointed_relieved: ), so no biggie. 

The other thing I've found so far is that the definition of the errors has in fact moved from `backend.driver` to `dbapi.exceptions`.

**Comment by philchristensen** [comment]
IMO, it's nice when libraries re-import useful classes into the top-level package. Maybe we could take that approach for stuff like Exceptions.

**Comment by hynekcer** [comment]
I was thinking more about an useful part of hierarchy of [exceptions from Python DB API 2.0](https://www.python.org/dev/peps/pep-0249/#exceptions) and what could need users and for which type of problems should be raised Django exceptions, than about specifying them now pretended by to import.

@dhbahr, please what is important to discriminate between exceptions (and what not) for example for you?

I'm thinking maybe no special class will be raised in January 2020 in a version updated for Django 3.0 and everything could be wrapped by Django exception classes, similarly to other backends, or by some their subclasses. Raw db exceptions will be raised only if a raw dbapi cursor will be opened directly, not wrapped by Django e.g. by `django.db.connections['salesforce'].cursor()`. I have these reasons why I don't wrap it now and not re-raise the exceptions:
* To stabilize the behavior, to get a feedback, to decide what is useful or not.
* Other backends have a C driver without a useful traceback.
* We still support Python 2.7, that is without a good re-raise.

I expect no special version for Django 2.2 because all test passed just now also on RC1 version. A probable bug fix version 0.8.x could be useful at the end of June, then I will disregard Python 2.7, Django 1.x and to implement what was postponed due to it and to prepare for Django 3.0.

I'm going to commit some `salesforce.***Error`, but it could be also not a long time solution and it could must be removed later to not become confusing.

**Comment by dhbahr** [comment]
@hynekcer please don't get me wrong, I'm not complaining because you moved the exceptions, all I'm saying is that these changes could be published on the release notes so that, when migrating from a previous version, devs know what they need to account for.

In my case I'm using the `SalesforceException` in a form, to make sure I display error messages from ValidationRules under the appropriate field (depending on a dropdown on the form some fields are required or not).

**Comment by hynekcer** [comment]
The most important change is that it is much more compatible with Django and more data conversions are done by Django, not by django-salesforce and that the most internal layer `salesforce.dbapi` is completely independent on Django and doesn't require it to be installed. It is not easy to describe that 
and not describe unimportant details because also Django django doesn't describe easy things. It must come now from outside by issues.

A big part of module `backend.driver` between v0.7.2 and  v0.8 was only a stub and a code unused in production, only to have common points with a development branch if any change should be done in both branches to be not too different. Many code was good enough for public usage.) The module `dbapi.driver` is approximately a half of Python DB API 2.0, with implemented `cursor.execute("SELECT ...`, but insert, update and delete are implemented in the old good way hooked directly in Django Query (SalesforceQuery) class without an SQL alternative. It is possible to update 200 objects together by one request by their dictionaries field/value (even objects of different types), but no mass SQL command syntax exists for it.

**Comment by hynekcer** [comment]
I wrote a CHANGELOG file (#228) after your issue. That is a more universal basic text useful for non trivial upgrades.

(Maybe I can remember a new requirement for a future refactoring of tests, that an old test project with some subset of old simple tests should work also with a new version of framework. If it will not work then upgrade notes will be necessary. Currently I'm testing the public API together with internals of the framework in order to minimize the number of necessary tests, because a test setUp/tearDown is relative slow with Salesforce. A small subset of tests would cover probably only a basic usage, not issues similar to this one.)

I vote for close.

**Comment by dhbahr** [comment]
Looks good to me, thanks for your efforts. I took the liberty to suggest a few editions to the content, feel free to (dis)regard them as you see fit.
