### ISSUE TITLE
Using custom request

### ISSUE THREAD

**Issue by Blekely** [django-salesforce/django-salesforce#229]
Hi, Is there a way to access the request session that makes the call to salesforce in a view?

I am trying to use this package with OpenId credentials.  Ultimately would like to do something like this:
```
def my_accounts(request):
    session = requests.Session()
    session.headers.update(...)
    Account.objects(session=session).all()
```

Thanks

**Comment by philchristensen** [comment]
I’m not fully up to date on what OpenID integration SFDC provides, but I’m not sure this would be a supported use case.

You’d still want to associate the connection with an “Application” in Salesforce, so you’d still end up getting OAuth keys generated.

Also, I personally prefer relying on the security code instead of whitelisting IPs, and I’m not sure how this would work if you are skipping the Salesforce authenticator.

@hynekcer may have deeper insight...

**Comment by Blekely** [comment]
Thanks for the quick response.
I am using this authentication flow [here](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_web_server_oauth_flow.htm)
But I'm not suggesting managing the authentication flow in this package.  I'm just looking for a way to update the request session from a view post authentication.

Currently I'm using: 
```
from simple_salesforce import Salesforce
def my_accounts(request):
    sf = Salesforce(instance=request.user.instance, session_id=request.user.session_id)
    sf.query("SELECT ...")
    ...
```
But using simple-salesforce means writing lots of SOQL. 

As a backup plan I may go this route
```
from simple_salesforce import Salesforce
def my_accounts(request):
    sf = Salesforce(instance=request.user.instance, session_id=request.user.session_id)
    accounts = Account.objects.all()
    sf.query(accounts.query)
    ...
```

**Comment by philchristensen** [comment]
Interesting...I have an idea but I'm not near my dev workstation, so you might have to experiment a bit.

The `requests` session object in question is [deep inside the RawConnection object](django-salesforce/django-salesforce/blob/master/salesforce/dbapi/driver.py#L159) that simulates the Python DB API. I *think* you can do something like this:

```
from django.db import connections

conn = connections['salesforce']
conn.sf_session.headers.update(...)
```

This should work fine within a view or something, since the auth/connection happens at the beginning of the Django run by default. There's some experimental and edge features in django-salesforce (like lazy loading and dynamic authentication) that probably would clobber this header, so that's worth remembering if your usage becomes more sophisticated.

**Comment by hynekcer** [comment]
This is exactly what "dynamic authentication" does:

``` python
connections['salesforce'].sf_session.auth.dynamic_start(access_token, instance_url=instance_url)
# some work...
connections['salesforce'].sf_session.auth.dynamic_end()
# forgot the access token and optionally use the auth values that were valid before .dynamic_start(...)
```
It is regularly tested by `tests/test_dynamic_auth/tests.py`.

It should be thread safe to use different tokens/organizations in different in individual threads. That was tested manually four years ago, but no automated test exists.

---
Three years ago I wrote also a modified general `SalesforceAuth` that can work with a custom authentication class configurable by DATABASES settings, not on only the default SalesforcePasswordAuth or a direct work with tokens by auth.dynamic_start(), e.g. a class for interactive authentication by "Force.com CLI" by web browser, useful for development with Salesforce, without saving a password anywhere. It is not a part of production repository still and it is little obsoleted because SFDX is probably a better option now. If that solution would be committed then the dynamic auth probably will have to be enabled in settings to work.

**Comment by Blekely** [comment]
Thanks @philchristensen and @hynekcer, that does trick.
