### ISSUE TITLE
Bug with `select_related` with filter by children objects

### ISSUE THREAD

**Issue by jsma** [django-salesforce/django-salesforce#234]
I recently upgraded to django-salesforce 0.8 and updated my code to use `select_related` instead of `simple_select_related`. However, I have a management command that fetches data from Salesforce e.g.:

```
for contact_role in AccountContactRelation.objects.exclude(roles__isnull=True).select_related('contact'):
```

I now get the following error:

```
  for contact_role in AccountContactRelation.objects.exclude(roles__isnull=True).select_related('contact'):
File "/home/myuser/myproject/env/lib/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
  self._fetch_all()
File "/home/myuser/myproject/env/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
  self._result_cache = list(self._iterable_class(self))
File "/home/myuser/myproject/env/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
  results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
File "/home/myuser/myproject/env/lib/python3.6/site-packages/salesforce/backend/compiler.py", line 70, in execute_sql
  sql, params = self.as_sql()
File "/home/myuser/myproject/env/lib/python3.6/site-packages/salesforce/backend/compiler.py", line 149, in as_sql
  s_sql = '%s.%s' % (soql_trans[tab_name], col_name)

KeyError: ‘Contact’
```

Please let me know if there are more details I can provide to help troubleshoot this issue. Thanks for your work on updating this project to work with newer versions of Django!

**Comment by philchristensen** [comment]
I think it might be helpful to see the Model classes you're using for AccountContactRelation and Contact.

**Comment by hynekcer** [comment]
The model is not necessary. I reproduced that bug also on `testrunner.example.models` without any custom object:

    qs = Account.objects.filter(contact__isnull=True).select_related('owner')  # or 'Owner'

**Comment by hynekcer** [comment]
The following general solution for our example.models can be probably easily applied to your models. 

There are two ways to fix the problem:

**1) Emulate a solution similar to the old `simple_select_related(...)` method**:

      qs_ids = list(set(Contact.objects.values_list('account_id', flat=True)))
      qs = Account.objects.filter(pk__in=qs_ids).select_related('owner'):

The method `simple_select_related` was a temporary solution, that worked by running two querysets similarly. It fails if the list of keys `qs_ids` is too big (about 500 rows). Therefore it is restricted by `set()` to prevent duplicated keys.

The selected fields can be then restricted by values() method: `.select_related('owner').values('name', 'owner__username',...)` while the method simple_select_related() required to add fields individually.

**2) Use a queryset with subquery**:

    subquery = Contact.objects.filter().values('account_id')
    qs = Account.objects.filter(pk__in=subquery).select_related('owner')  # or 'Owner'

That is all run by one SQL request and there is no restriction by a number of keys. It requires the today's patch included in version 0.8.1

---

Notes:
---------

Neither Django default databases do not compile this correctly:

    >>> qs = Account.objects.exclude(contact__isnull=True).select_related('owner')
    >>> print(str(qs.query.get_compiler('default').as_sql()))
    SELECT Account.Id, ... FROM Account
    INNER JOIN Contact ON (Account.Id = Contact.AccountId)
    INNER JOIN User ON (Account.OwnerId = User.Id) WHERE Contact.Id IS NOT NULL

See that this every Account is incorrectly duplicated by the number of its Contacts. I never expected a filter condition on a child object combined with `select_related` method to be compiled by a simple SQL. 

---
 
Restrictions on subqueries by Salesforce:
> **Subquery Limits** [[docs](https://developer.salesforce.com/docs/atlas.en-us.220.0.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_comparisonoperators.htm)]
> * ...
> * The selected column in a subquery must be a foreign key field, and cannot traverse relationships. This limit means that you cannot use dot notation in a selected field of a subquery.

Example of invalid subquery:

    >>> subquery = Account.objects.filter(contact__isnull=True).values('pk')
    >>> list(Account.objects.filter(pk__in=subquery).select_related('Owner'))
    SalesforceError: MALFORMED_QUERY
    
    FROM Account WHERE Account.Id IN (SELECT Contact.Account.Id FROM Contact)
                                             ^
    ERROR at Row:1:Column:250
    The inner select field 'Contact.Account.Id' cannot have more than one level of
    relationships

While this is supported by SFDC:

    subquery = Contact.objects.filter().values('account_id')

because it is compiled to:

    FROM Account WHERE Account.Id IN (SELECT Contact.AccountId FROM Contact)

(see the small difference `AccountId` vs. `Account.Id`)

---

`Account` model exported by `inspectdb` has a field `owner = ForeignKey(User,...)` with a lowercase name by Django convention. Some people prefer Salesforce convention with camel-case field names like 'Owner' that is demonstrated in example.models in some classes. The name used in the queryset should match the used model.

---

I expect about your model that your Contact can have relationships to more Accounts through an intermediary object AccountContactRelation and this relationship AccountContactRelation can have more "roles" to that Account. The name "roles" is reverse relationship.

**Comment by hynekcer** [comment]
**@jsma**: I expected about your model AccountContactRelation that your Contact can have a relationship to more Accounts through an intermediary object AccountContactRelation and this relationship AccountContactRelation can have more "roles" to that Account and the name "roles" is a reverse relationship.

**Comment by jsma** [comment]
Thanks for the quick turnaround! I've tested 0.8.1 and it appears to have fixed the issue for me. 

FYI, it wasn't actually a custom object, it's a [built-in](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_accountcontactrelation.htm#!) (in Lightning only) and `roles` is simply a picklist.

Thanks again!

**Comment by philchristensen** [comment]
No problem. Thanks for the report and for testing the release!
