### ISSUE TITLE
FAIL: test_time_field (salesforce.tests.test_integration.BasicSOQLRoTest)

### ISSUE THREAD

**Issue by philchristensen** [django-salesforce/django-salesforce#242]
Getting a strange failure from the unit tests across all versions. The test pipeline was re-triggered after I added the GitHub Sponsors config.

```
Test a TimeField (read, modify, verify).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/tests/test_integration.py", line 493, in test_time_field
    self.assertEqual(obj.MondayStartTime, datetime.time(23, 59))
AssertionError: datetime.time(7, 59) != datetime.time(23, 59)
```

I've got no idea at all why the Monday start time would change.

**Comment by hynekcer** [comment]
Salesforce version Winter '20 requires the commit 40ec03b from hynekcer-for-new-version branch (added letter Z in JSON for TimeField to prevent a time shift by a time zone of the Organization. I think that it is a silly "improvement" by Salesforce if they interpret a value as a local time by default and they return everything converted to UTC. Every value saved by their web interface, e.g. an opening time 8 am is saved as 8 UTC, retrieved as 8 UTC and displayed on the web again as 8 am.) It was not too important because a TimeField can be used only with built-in BusinessHours object. Nobody set it probably by API.

It can be fixed by merging.
