### ISSUE TITLE
How do I iterate over a queryset?

### ISSUE THREAD

**Issue by elliott-maguire** [django-salesforce/django-salesforce#249]
I'm working on a DRF API that integrates with Salesforce for a few objects using `django-salesforce`. I'm trying to get serialization working for a certain endpoint, but can't manage to iterate over a queryset.

I've got some queries:

    contact = Contact.objects.get(email="j.doe@testing.co") # Works fine, grabs the right contact
    cases = Case.objects.filter(contact=contact) # Returns a SalesforceQuerySet instance

If I try to iterate over it in any way (i.e. `for case in cases: ...` or a list comprehension), it throws this:

    File ".../salesforce/backend/compiler.py", line 260, in query_topology
        assert join_cols[1] == 'Id'
    AssertionError

I have `SF_PK` set to `"id"` in `settings.py`.

As far as I can tell, the `SalesforceQuerySet` object inherits from the default Django `QuerySet` object, and therefore should be iterable just the same, but the issue seems to arise when it's attempting to compile the SOQL. Am I missing a step or call somewhere? Or is this not possible?

**Comment by hynekcer** [comment]
The issue requires more information because both variants are supported in the simplified case that you described. (the default 'id' and the backward compatible less tested 'Id'`)

These details could be important:
A) if a primary key is added manually incorrectly, not created automatically. (why?)
B) a migration exists for the application that define the salesforce database models. (The setting SF_PK should not be changed after you create a first migration. If you change it then all migrations of salesforce models must be deleted and a new initial migration must be created from the current state. This is usually easy without disadvantage.)

If it doesn't help then write the line that contains the primary key of Contact in the model and in the migrations files. Versions can be also useful if they are not the latest releases.

The problem is not an iteration, but an evaluation of the queryset e.g. its length, because the evaluation is lazy. You can chain more filters at the end of a queryset and only the final queryset is compiled to SOQL and executed.

**Comment by elliott-maguire** [comment]
Yeah it definitely was issues with the migrations, thank you!
