### ISSUE TITLE
Make the local salesforce db use primary keys like salesforce does

### ISSUE THREAD

**Issue by stefanfoulis** [django-salesforce/django-salesforce#251]
Currently the local salesforce db uses integers for the foreign keys to other salesforce objects when using the local db. It would be more accurate for testing if it used a similar format as salesforce does:
A string rather than an integer. Perhaps even using the same random-ish value that salesforce generates, so we could validate the format in django.

**Comment by hynekcer** [comment]
OK. We can do it **configurable** by django.conf.settings. I remember a PR #232 where it was only mandatory and it was therefore rejected. (see the reasons there) Try that simple PR. I remember that I have also a version with a random hash primary key if a SalesforceModel object is saved to a local database without a primary key.

I must be optional also because it will probably cause some issues that could be not outbalanced by benefits for xome users

I suggest a settings variable `SF_NONSF_PK_TYPE'. It expresses that it is a primary key setting related to Salesforce only if it is used as non-Salesforce (it is not a change related to standard Django models and it is also not related to objects saved into SFDC cloud.

**Comment by hynekcer** [comment]
Maybe it should be better as a `nonsf_pk_type` attribute in `Meta` class of the model, because it is a database change and it is desirable that a migration will be created.

**Comment by hynekcer** [comment]
It is a standard part of v0.9. Try to use the module `salesforce.models_extend` instead of `salesforce.models`. It can be very easily changed by one word. A short documentation can be found at the beginning of the file. A test for it can be found in a directory `tests/test_default_db`.

I appreciate if you find possible issues. I will not try to integrate it directly into models until it is proved by more users.

---

Salesforce ID is not random, but semi-sequential ordered in "C" sorting order: Object prefix + identifier of server instance where the object has been created + sequential identifier + 3 characters encoded lower/upper-case of the previous 15 characters (see case_safe_sf_id(id_15) -> id_18): The object prefix is unpredictable for custom objects and can be different for the same object type in different organizations, even on the same server instance. Therefore I use simply a random UUID to be possible easily  differentiate objects cloned from SFDC to the local database and objects created only in the local database.

**Comment by hynekcer** [comment]
I fixed the problem by writing a wiki page [SalesforceModels used with local databases](https://github.com/django-salesforce/django-salesforce/wiki/SalesforceModels-used-with-local-databases) and declaring that the module `salesforce.models_extend` is public now.

Closing. If necessary, create a new issue related to models_extend.

(crossed out my alternative old proposals here)
