### ISSUE TITLE
Dynamic Auth still requires CONSUMER_KEY, CONSUMER_SECRET etc. to be set in settings

### ISSUE THREAD

**Issue by sondrewb** [django-salesforce/django-salesforce#266]
First of all, great library. Worked really well out of the box.

I am using the [dynamic authorization](https://github.com/django-salesforce/django-salesforce/wiki/Experimental-Features#dynamic-authorization) and I do manage to get it to work on a request etc. as specificed in the docs.

However, when I try to change the database settings to be 'AUTH': 'salesforce.auth.DynamicAuth', as recommended, I am still getting errors in the validation of the settings.

Is it something I am missing or does the validation not work with experimental features?

**Comment by hynekcer** [comment]
You can find an example for dynamic auth in the file `tests/test_dynamic_auth/settings.py`.
``` python
SF_LAZY_CONNECT = True
DATABASES = {
    'salesforce': {
        'ENGINE': 'salesforce.backend', 
        'HOST': 'https://nonsense.example.com',  # an invalid URL on your domain
        'CONSUMER_KEY': '.',                     # any non empty string
        'CONSUMER_SECRET': '.',                  # any non empty string
        'USER': 'dynamic auth',                  # any non empty string
        'PASSWORD': '.',                         # any non empty string
    }
}
```
---
It is the endless fight between omitting to write documentation and writing it before a stable implementation or even before the new implementation is committed to the master.

The first implementation was in year 2014 by methods `dynamic_start(access_token, instance_url=None)` and `dynamic_stop()` to switch between the original state (static authorization, either valid or with and invalid HOST url and with setting `SF_LAZY_CONNECT = True` so that it never try to connect automatically at start up before the first request initiated by you). That implementation was thoroughly tested by some client that it is thread safe and different users can work even with different SFDC instances in different threads of the same process without a race condition problem. The assignment was, that an expiration of the token can be neglected because the token is never too old and command dynamic_stop() will be run relatively soon.

I wrote an implementation of configurable `DynamicAuth(SalesforceAuth)` and `ForceComCliAuth` in 2016 in some currently obsoleted branches (e.g. [hynekcer/development](https://github.com/hynekcer/django-salesforce/tree/development) and wrote about it to Wiki like to "throw a fishing rod", but nothing from "Experimental" had no feedback in the next two years. It was better to leave it in obsolete code and concentrate to more important features.

I put the wiki back a little to the current old implementation, but I don't want to give up that idea completely.

The biggest issue of this project is no financing in last 5 years, neither indirect. It grows only from a mental satisfaction when a solution seems good. There is now a button "**&#9825;** Sponsor" since the beginning of May and currently less than $15 per month is promised. Please, support it if you like this library.

**Comment by sondrewb** [comment]
@hynekcer Thanks for the quick and good response. I did end up just leaving the uneeded keys blank as you suggested above. 

I am planning on using this experimental feature somewhat extensively (and yes, I am well aware that I am doing so at my own risk, and I do not expect nothing from you guys ;-)). I might end up creating my own fork, and if I do any interesting will make a PR upstream.

**Comment by hynekcer** [comment]
This solution with dynamic_start() dynamic_end() and nonsense host is a classic and stable solution, actually not experimental. It is guaranteed that it remain in a compatible form for long time.

You can get 401 in a longer code, e.g. in `bulk_create(...)`. You can not easily stop, reauthenticate and start again. It is more work. It is against readability. Only two solutions are good:

- add a callback parameter to `dynamic_start()` that helps you to get a new token and to continue smoothly.
- to monitor the age of token and to renew it before a request if it was not used e.g. for 15 minutes.

I have a similar code with a ping request `ping_connection()` it is a very fast request if the connection is good, cca 30 ms and it has a maximal possible timeout 1 second and the connection is reset after the timeout. It is not smart to run a normal command with a long timeout after a long pause. It works well now even if I travel with a notebook and I don't need to set a retry requests number.

If I remember about password authentication, a login is very fast it a token exists before a half of time life, otherwise a new token is created.

**Comment by hynekcer** [comment]
Pre-release 1.1 is prepared. I would be glad if you write a feedback about the rewritten authentication.
I refactored all uncommitted authentication code to the new codebase to implement most ideas from the wiki. The rest is edited. The most important changes:

* AUTH is so configurable that also a custom auth code can be used. Everything except a basic password auth must he explicitly declared.
* Static and dynamic auth code are separated to make it simpler. (as two main branches of the class hierarchy with one parent auth class) Configuration is minimalistic, without any nonsense non empty value. 
* If the token is invalid (401), then a custom reauthenticate() is called. If an empty value is returned instead of valid token, then 401 is raised, otherwise the operation is retried with the new token.

An important motivation was a chance that you will implement the dynamic auth soon with the new code

**Comment by hynekcer** [comment]
I think that everything related to authentication is fixed: documentation Wiki, refactoring to more customizable structure, fixed all TODO in the auth code, new types of authenticaton prepared in master for version 1.1 and one in a new PR. Feel free to ask.
