### ISSUE TITLE
Possible to reuse SOAP session token?

### ISSUE THREAD

**Issue by brno32** [django-salesforce/django-salesforce#282]
Hello. For my integrations, I usually just connect directly via an integration user, using only the username, password, and security token, no oauth involved.

Is it possible to do this with this library?

**Comment by philchristensen** [comment]
No, we use the SFDC REST API, which requires OAuth.

**Comment by brno32** [comment]
I usually connect via `simple-salesforce` which is calling the REST API under the hood. It hits endpoints like this:
`https://{instance}/services/data/v{sf_version}/sobjects/{sobject}/`
which looks like the endpoint from the [REST example](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_usage_rest_resources.htm).

Looking at the `simple-salesforce` code, it looks like the login happens via the SOAP api, whereby the session token is then passed on to REST. This library doesn't currently support that, correct?

**Comment by philchristensen** [comment]
Actually I have a vague recollection of this SOAP/REST usage being requested before. @hynekcer would have the most insight.

**Comment by brno32** [comment]
If this is wanted, I'd be happy to open a PR if someone could point me to the relevant spot in the code!

**Comment by hynekcer** [comment]
Authentication in django-salesforce is modular. Anybody can easily create a custom authentication module without changing the source. I think that more builtin authentication methods are currently implemented than in simple-salesforce, e.g. completely without a password, only by a refresh token. It is described in wiki
[Configurable authentication/authorization methods](https://github.com/django-salesforce/django-salesforce/wiki/Experimental-Features#configurable-authenticationauthorization-methods).

If you want to reuse the token from simple-salesforce login, you can use "[Dynamic authentication](https://github.com/django-salesforce/django-salesforce/wiki/Experimental-Features#dynamic-authentication)" described there. It is used usually if every web request can have a different user, but you can leave the same user all the time and you never need to forget the token by calling the `.dynamic_end()` method.

I can look at a simple SOAP login on Monday and decide if we add it directly or maybe not for security reasons, because I read:
> OAuth access token authentication is the most secure way to authenticate SOAP API calls. ([Authenticate Your SOAP API Calls](https://developer.salesforce.com/docs/atlas.en-us.mc-apis.meta/mc-apis/authenticate-soap-api.htm))

An administrator can restrict access in OAuth only to some external apps by consumer keys. SOAP API is older and old authentication methods are probably supported for compatibility reasons.

**Comment by tsabat** [comment]
I could use this functionality as well.

**Comment by hynekcer** [comment]
A simple SOAP authentication by django-salesforce with only password without OAuth is similar to `simple-salesforce`. It is now possible with these settings:
``` python
DATABASES = {'salesforce': {
    'ENGINE':   'salesforce.backend',
    'AUTH':     'salesforce.auth.SimpleSfPasswordAuth',
    'USER':     '',
    'PASSWORD': '',    # including the personal security_token
    'HOST': 'https://login.salesforce.com',   # or 'https://test.salesforce.com' for sandbox
}}
```
Everything new is in the commit [SOAP authentication SimpleSfPasswordAuth similar to simple-salesforce](https://github.com/django-salesforce/django-salesforce/commit/315f978f765222e814995f469d30d77d8990156b). You can upgrade from github or simply copy that `auth.py` module elsewhere and use it in 'AUTH' settings.

So, the SOAP token can really be reused. :-)
