### ISSUE TITLE
Can't run migrations in Django 3.2 when changing HOST

### ISSUE THREAD

**Issue by kunambi** [django-salesforce/django-salesforce#287]
From `pipenv graph`:
```bash
django-salesforce==3.2
  - django [required: >=2.0, installed: 3.2.3]
    - asgiref [required: >=3.3.2,<4, installed: 3.3.4]
    - pytz [required: Any, installed: 2021.1]
    - sqlparse [required: >=0.2.2, installed: 0.4.1]
  - pytz [required: >=2012c, installed: 2021.1]
  - requests [required: >=2.4.0, installed: 2.25.1]
    - certifi [required: >=2017.4.17, installed: 2021.5.30]
    - chardet [required: >=3.0.2,<5, installed: 4.0.0]
    - idna [required: >=2.5,<3, installed: 2.10]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.5]
  - simplejson [required: >=2.5.0, installed: 3.17.2]
```

The `HOST` setting is pointing to `https://test.salesforce.com`

Traceback when running `./manage.py makemigrations`:
```bash
  # ...
  File "C:\Users\Owner\.virtualenvs\6P0nJig8\lib\site-packages\salesforce\auth.py", line 291, in authenticate
    return self.checked_auth_response(response)
  File "C:\Users\Owner\.virtualenvs\6P0nJig8\lib\site-packages\salesforce\auth.py", line 211, in checked_auth_response
    raise SalesforceAuthError("oauth failed: %s: %s" % (self.settings_dict['USER'], response.text))
salesforce.dbapi.exceptions.SalesforceAuthError: oauth failed: ***@***.com: {"error":"invalid_grant","error_description":"authentication failure"}
```

Changing the `HOST` setting back to `https://login.salesforce.com` allows `./manage.py makemigrations` to run smoothly.

## Expected behaviour:

* I understand that we get the error because the user credentials are for the production server, but there should be no calls to your servers what-so-ever during `./manage.py makemigrations` imho thus no errors should be thrown.

**Comment by hynekcer** [comment]
The command `makemigrations` requires all databases connections because it besides other things also verifies the consistency of migration history of all connected databases. Our Salesforce driver claims that the migration history is empty (that implies consistent) without asking SFDC, but Django creates all connections automatically before it.

The problem can not be reproduced. It is strange that the exception `SalesforceAuthError("oauth failed: ...)` is raised inside `checked_auth_response()`, because it is only an additional verification of response integrity. It is something like to verify "1+1 = 2" with cryptography. All your secrets in the login request were probably valid if `response.status_code == 200` and also that the name `USER` was modified correctly for the sandbox.

I suggest to rename "Can't run migrations" to "Can't connect", because the command is not important and everything fails probably similarly.
``` python
$ python manage.py shell
>>> from django.db import connections
>>> cursor = connections['salesforce'].cursor()
```

* It is useful to create a fresh sanbox. (It has the same CONSUMER_KEY, CONSUMER_SECRET and PASSWORD, only the HOST and USER are different.)
* You can try to replace the line ` raise SalesforceAuthError(...)` by noop `pass` command.
* I expect that you use the default authentication `{'AUTH': 'salesforcce.auth.SalesforcePasswordAuth',...}` in `DATABASES['salesforce']` if you install django-salesforce from Github you can use a simple {'AUTH': 'salesforcce.auth.SimpleSfPasswordAuth' ...` that doesn't need OAuth consumer key and secret.
* Verify that you can login to sandbox with the same auth data by some other software that uses API login.

**Comment by hynekcer** [comment]
I answered this better on the wiki [How torun makemigrations without conectivity to Salesforce.com](https://github.com/django-salesforce/django-salesforce/wiki/How-to-run-makemigrations-without-conectivity-to-Salesforce.com).
