### ISSUE TITLE
Want to add typing information? 

### ISSUE THREAD

**Issue by sebastian-philipp** [django-salesforce/django-salesforce#307]
I'm getting this error here: 

```
common_services/salesforce_models.py:2: error: Skipping analyzing "salesforce.models": module is installed, but missing library stubs or py.typed marker
common_services/salesforce_models.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 12 source files)
```

Would be super awesome to get some typing information from django-salesforce

**Comment by philchristensen** [comment]
That it would! MRs are eagerly encouraged ;-)

**Comment by hynekcer** [comment]
Stubs for Django-salesforce are in https://github.com/hynekcer/django-salesforce-stubs.git . It is a customized https://github.com/typeddjango/django-stubs version 1.5.0 (March 2020) extended for django-salesforce. It requires `mypy 0.770` (exact version, not newer)

If you add the following dependencies then your models will be typed and also normal Django models are typed by it:
```
    mypy==0.770
    git+https://github.com/hynekcer/django-salesforce-stubs.git@v1.5.0.3#django-stubs
```

The versions remain still locked because it works well also with the newest versions of Django and Python. Django-stubs is a complicated dynamic package, but Django-salesforce extensively typed and is uses more internal types of Django that are implemented by django-subs.

The stubs haven't had any feedback yet. I will appreciate a sponsorship of django-salesforce. (by a sponsor button here)

**Comment by philchristensen** [comment]
D'oh! I knew that existed and totally forgot. Still early for me ;-)
