### ISSUE TITLE
REQUEST_LIMIT_EXCEEDED due to N+1 query

### ISSUE THREAD

**Issue by sebastian-philipp** [django-salesforce/django-salesforce#317]
Hey there, 

we made a mistake in our Django Admin Page and ended up with a REQUEST_LIMIT_EXCEEDED for today. Are there any best practices or mitigation strategies (Except for, well, not doing those mistakes)?

There is already a `request_count` variable in `handle_api_exceptions_inter`. Do you think having a 10000 per 30 minute request limit that raises an exception might be an idea?

**Comment by hynekcer** [comment]
Yes, `request_count` variable is useful to find greedy bugs in your code early. A safe value depends on the API requests limit in your Salesforce instance and on many circumstances.

The variable `request_count` however doesn't help you to know that you are close to a problem. That is unsure if your server use more processes of your application or if they have been restarted more times per day or if you  have already consciously done something extensive that day.

I would recommend another solution that I implemented today. Every API request (counted to daily limits) gets a `Sforce-Limit-Info` response header. I monitor it in an `api_usage` attribute. You can use it this way:

``` python
# maybe you want a warning if more than 50% API resources is consumed
api_usage = django.db.connections['salesforce'].connection.api_usage
if api_usage.api_usage / api_usage.api_limit > 0.5:
    print("Warning ...")
```
You should not test `api_usage` before the first request after startup, otherwise the connection is None and api_usage is undefined.

My experience is that the value `api_usage` an approximate floating sum per 24 hours updated every some minutes. It is possible that it will slowly decrease soon if the traffic is small again.

**Comment by hynekcer** [comment]
Merged "Monitoring 'api_usage' ...".
