### ISSUE TITLE
Compatibility with Django 4.2

### ISSUE THREAD

**Issue by joshuadavidthomas** [django-salesforce/django-salesforce#320]
Django 4.2 was released just over a month ago. This package has a check in `salesforce/backend/__init__.py` that prevents using it with the newest version. (There is no enforcement of the version constraint in the package's `setup.py`.)

4.2 introduced some breaking changes for the database backend API -- https://docs.djangoproject.com/en/4.2/releases/4.2/#database-backend-api -- that may need to be dealt with.

**Comment by philchristensen** [comment]
There’s no specific timeline for release, as this project has a very small support team.

Users with production timelines impacted by this are encouraged to leverage the GitLab sponsorships system, which directly funds the primary developer of this project. You may also wish to DM @hynekcer directly.

**Comment by joshuadavidthomas** [comment]
Thanks for the quick response! Are the maintainers open to an outside PR to tackle this? If so I may take a crack at it, time permitting.

Thanks to all the contributors and maintainers for this package! 😄

**Comment by philchristensen** [comment]
Oh, PRs are encouraged and appreciated!

**Comment by hynekcer** [comment]
I prepared a fix for Django 4.2 on March 15th. The problem is that this project has very few sponsors and little total contribution, as you can see on the page https://github.com/sponsors/hynekcer.

I am thinking about incentives for sponsors. Words alone did not help enough. My idea is to continue this project in two very similar repositories under two licenses. One repository with unrestricted code under very a restrictive license AGPL (GNU Affero General Public License - which  requires to share every code that uses it including e.g. any web application) and this repository will continue unchanged under MIT license, but some new code in this repository added after April 2023 would call a function "sponsor_motivation()" that will pass silently if you have a sponsor code in your settings or it rejects to continue.

The restricted code should be usually support for the newest stable Django version (development Django versions remain unrestricted) and Django migrations. I have been using migrations for two years and I think that it is a very useful part of a development with Django, but it will require sponsors so that it is reasonable to solve possible secondary problems.

Please [write me](mailto:hynek@sdb.cz) what should be a part of your sponsor code (a company name and a contact email to you).

**Comment by hynekcer** [comment]
Version 4.2 that is compatible with Django 4.2 has been released yesterday. See the README about license alternative or ask for a license key.
