### ISSUE TITLE
no attribute 'XJSONField'

### ISSUE THREAD

**Issue by b-stead** [django-salesforce/django-salesforce#329]
I have suddenly got a new error that wasn't a problem before, have tried to retrace my steps but cannot find the issue.

I'm running with Django 4.0.6 and Django-salesforce 4.1

File "/Users/brendonstead/Desktop/Kinnelhead/SEO/seo-usa-portal/usaportal/accounts/urls.py", line 4, in <module>
    from accounts import views
  File "/Users/brendonstead/Desktop/Kinnelhead/SEO/seo-usa-portal/usaportal/accounts/views.py", line 3, in <module>
    from core.salesforce_models import Account
  File "/Users/brendonstead/Desktop/Kinnelhead/SEO/seo-usa-portal/usaportal/core/salesforce_models.py", line 11912, in <module>
    class EntityDefinition(models.Model):
  File "/Users/brendonstead/Desktop/Kinnelhead/SEO/seo-usa-portal/usaportal/core/salesforce_models.py", line 11952, in EntityDefinition
    recordtypessupported = models.XJSONField(db_column='RecordTypesSupported', blank=True, null=True)  # Field name made lowercase.
                           ^^^^^^^^^^^^^^^^^
AttributeError: module 'django.db.models' has no attribute 'XJSONField'. Did you mean: 'JSONField'?

I have a separate version which works and has no issue with the XJSON field?

**Comment by hynekcer** [comment]
Your problem is that you probably mix Salesforce models created from an existing Salesforce database by `manage.py inspectdb --database=salesforce` with a normal Django model for standard databases. An exported file `models.py` for Salesforce starts with a line `from salesforce import models` and it should not be replaced by a line `from django.db import models`.

I recommend you to delete Models that you do not need or to select only explicit names that you use by `manage.py inspectdb --database=salesforce SomeModel CustomModel__c OtherModel...`.

The field `salesforce.models.XJSONField` is a counterpart of an Salesforce internal "complexvalue" field type that is used only by [User Interface API](https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/) or by [Tooling API](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/) for work with metadata. `EntityDefinition` and `FieldDefinition` are accessible also by a standard API in recent Salesforce versions, but you probably do not need them.

My docs string for`XJSONField`:

    Salesforce internal "complexvalue" field similar to JSON, used by SFDC for metadata,

    this field should not be used for normal data or with other database backends.

(Have you ever thought about sponsoring this project? It is easy with "Sponsor" button on the project home page.)
