### ISSUE TITLE
Sponsorship license key

### ISSUE THREAD

**Issue by tituspeterson** [django-salesforce/django-salesforce#331]
I am interested in testing out this lib (but need it to work on django 4.2), so I added a sponsorship. Is there any documentation on how to obtain the license key after that?

**Comment by philchristensen** [comment]
Thanks very much! @hynekcer will reach out to you shortly with the license key. I'd give him about a day just because of timezones, etc.

**Comment by hynekcer** [comment]
Thank you for your sponsorhip. That is important for sustainability of this project. By chance you can use this package with Django 4.2 today even without a licence key if you download Django-salesforce 5.0, that has been published yesterday. Django 4.2 is unlocked there because Django 5.0 is a mainstream version as of December 4th.

If you like this package please write me an email at [hynek@sdb.cz](mailto:hynek@sdb.cz). A name of person or company of a license holder and a contact email will be included in the licence key. The license key is always permanent for the same Django version (5.0 now). If you continue to contribute until new versions of Django and django-salesforce are released, it will remain valid also for them. A recommended contribution is $10 a month or $50 one-time. (You can see that this project has only six sponsors including you. Documentation will be written.)

Everybody can try django-salesforce with new development Django versions (currently Django 5.1 alpha) and report possible issues.

**Comment by tituspeterson** [comment]
Awesome thanks for the info, I'll reach out after we check it out on 4.2
