### ISSUE TITLE
django-salesforce-agpl 

### ISSUE THREAD

**Issue by yleniarotalinti** [django-salesforce/django-salesforce#337]
Hi, 
I'm using python 3.11.6 and Django 5.0.6. 
GIven that, I'm using django-salesforce-agpl instead of django-salesforce. 

How do I : from salesforce.models import SalesforceModel in my models.py script? 

Thank you in advance. 
Ylenia

**Comment by philchristensen** [comment]
Sorry, it’s a little unclear what issue you’re running into. Are you getting an error of some kind?

**Comment by philchristensen** [comment]
There’s  no meaningful difference between libraries except licensing. There’s no difference in the import process or library names.

**Comment by hynekcer** [comment]
@yleniarotalinti

A) Verify some elementar preconditions for Django: 
- You have no other package with the name "salesforce" and no directory "salesforce" in the root of your project. Try to run `import salesforce` and `print(salesforce)`. You will see if it is the directory where django-salesforce was installed.
- Try to run `from django.conf import settings`

B) I see other problems in your example after you fix the import of our models:
I  recommend `from salesforce import models` instead of your `from django.db import models` because you need to use also some field types adapted for Salesforce. A simple django.db.models.CharField could be used only if you specify a `db_column` parameter. The original ForeignKey can be never used in a Salesforce model. The module `salesforce.models` works well also with other databases but `django.db.models` shouldn'ť be used with Salesforce. You also need `db_table` attribute in `Meta` of your model, because "Person" will be a "custom object" in Salesforce. The easiest is to start from `inspectdb` and verify that it works and simplify it. In your example:

    python manage.py inspectdb --database=salesforce Person__c
