### ISSUE TITLE
Dealing with Lead-Contact conversions

### ISSUE THREAD

**Issue by tvanesse** [django-salesforce/django-salesforce#94]
Hi guys,

I am currently struggling with [Lead-->Contact conversions](https://www.salesforce.com/developer/docs/api/Content/sforce_api_calls_convertlead.htm). I would like to do it from Django but it seems some fields related to this conversion are not writable. Namely `Lead.is_converted` and `Lead.converted_contact` have this `sf_read_only=models.NOT_UPDATEABLE` set.

Do you know how to deal with this Lead-->Contact conversion with `django-salesforce` properly?

Currently I have been trying to get it right with the following function

```python
def convert_lead(lead):
    """convert_lead
    Re-implement the `convertLead()` function using the Salesforce
    REST API. At the time this is written, `convertLead()` is only
    available through the SOAP (Apex) API.

    From the official documentation:

    > Convert a Lead into an Account and Contact, as well as (optionally)
    > an Opportunity.

    For the sake of this application, we only need to convert the Lead
    into a Contact.

    This function returns the newly created Contact.
    """
    if not lead.is_converted:
        # Convert the Lead into a Contact
        lead_serial = LeadSerializer(lead)
        contact_serial = ContactSerializer(data=lead_serial.data)

        if contact_serial.is_valid():
            c = contact_serial.object
            c.pk = None  # to avoid using the pk of the Lead instance
            c.save()
            lead.is_converted = True
            lead.status = 'Qualified - converted'
            lead.converted_contact = c
            lead.save()  # this fails (silently) to save the updated lead because of sf_read_only=models.NOT_UPDATEABLE on some fields
            return c
        else:
            # Should not happen
            raise RuntimeError(
                "The provided Lead could not be converted into a Contact.")
    else:
        # This Lead is already converted. Abort the mission.
        raise RuntimeWarning(
            "This Lead has already been converted.")
```

All the best.

**Comment by tvanesse** [comment]
From [`fields.py`](../blob/master/salesforce/fields.py) I see that 

> sf_read_only=1 (NOT_UPDATEABLE):  The field can be specified on insert but can not be later never modified. e.g. ContactId in User object (relative frequent)

and also that

> [...] describe fixed nature of SF standard objects that can not be modified no ways by no API or spell.

So I guess there is not so much we can do about it :sob:

**Comment by hynekcer** [comment]
Yes, Leads can be converted by SOAP API (your link above) or by Apex code or e.g. by an [custom extension to REST API written in Apex](http://salesforce.stackexchange.com/questions/50045/how-do-you-convert-a-lead-via-the-rest-api). I would like to add materialized template for the request, if someone prepare it, but I dislike to add too much code, WSDL etc, I will not incite it. I know also a solution how to upload and run Apex code from Python, but it could look like a backdoor for an uninformed user and so I never committed it to master branch and don't use it actively.

That my categoric "can not be modified" is meant about the attribute `sf_read_only` from point of view migrations. (Migrations are not implemetedin django-salesforce, theoretically thinkable and only a few simple succesful experiments has been made.) You can set in SF e.g. that a new field is "required" (null=False in Django), "unique" (unique=True), or case sensitive/insensitive (not mapped to any Django field attribute yet because no big problem with it), but `sf_read_only` is completely determined by SF attributes `updateable` and `createable` and doesn't make sense to map them to migrations because no API and no setup tool can modify them, as far as I know. They are fixed by SFDC,

If a field is "updateable" and "createable" it doesn't mean reliably that it is writable, because SFDC is complex, but I dont know a case where a read only field was not really read only. All "history"-like fields are usually read only, e.g. last_modified_date etc. Those mentioned are the history of Lead conversion.

**Comment by philchristensen** [comment]
It's actually surprising to me that there aren't more difficulties like this. The DB <=> Salesforce Model relationship we use is definitely a "Leaky Abstraction"; there are a variety of things in Salesforce that just don't make sense from a relational database perspective.

Trying to use the Django ORM mechanics for this looks kind of clunky, even if it did work.

I'd think the "Django way" to implement this would be a custom manager specifically for the Contact class that could accept a Lead instance with something like `c = Contact.objects.convert(lead)`

A different question is how that might work, but maybe a SOAP call to convert the lead, and then a regular ORM fetch to get the newly "created" Contact object?

Not sure what's involved in adding SOAP support these days. I picked REST because there wasn't much SOAP stuff for Python for awhile, but now https://github.com/pysimplesoap/pysimplesoap seems to have come a long way.

**Comment by hynekcer** [comment]
I can look at it in March. I wouldn't like to write much code neither to add new requirements. I think the sooner you do it yourself. Possibilities:

* If someone has installed [beatbox](https://pypi.python.org/pypi/beatbox/) then it can be used for this. It can be written on four lines according to readme, about ten lines including auth by django-salesforce credentials.. (I used that package before django-salesforce.)
* If someone wants to install a custom APEX code from any howto existing currently on the web then it can be used by django-salesforce.

I'm undecided between them and I'm open to both yet, until know what is acceptable for other people. I think that the same one of these should be used also for our future extensions, e.g. for insert and update of multiple SF objects.

Our interface of Lead conversion should be a simple function e.g. `convert_lead(lead, to='Contact', db='salesforce')`. I don't see a suitable class, because we can't know easily where the Contact or Lead models are implemented by the user, so we can't extend them. The user can add the function to his Lead.

I think that REST api was a good idea. New functionalities are added for REST-like APIs by SFDC, not for SOAP.

**Comment by tvanesse** [comment]
Now a question that comes to mind:

Is it worth the effort to integrate the Lead conversion with `beatbox` (or your second solution) if SFDC is going to add a Lead conversion endpoint in the REST API eventually? I guess it depends on how long we would have to wait before they release it, and I don't know if there is a public roadmap online regarding the REST API.

For what it's worth, it would be my pleasure to contribute to the implementation of the Lead conversion with either of the solutions mentioned, but I would need some guidance at the beginning.

**Comment by philchristensen** [comment]
I doubt that SFDC will add this feature into REST; it's just that if they *were* going to add features, it would be to REST, not SOAP.

I'd like to take a whack at beatbox integration to make this available myself, but I don't know that I have any more available time than Hynek does at this point.

Code submissions are always encouraged. My expectation is that this would be implemented as an optional custom Manager that can be mixed in to a SalesforceModel subclass.

**Comment by hynekcer** [comment]
@tvanesse A contribution is wellcome. Look at Beatbox Readme. Write a function that reads password etc. from django.conf.settings, logins by beatbox and converts a Lead or list of leads.

Write also a function that can be used as a test or as a core of the test. It can be later improved. Write a text for Readme. Maybe the spped will be good, maybe you find that it uses or can use the same type of acces token, maybe caching of the login must be added.

@philchristensen
I think that a good full integration to models can be complicated and not effective: It is related to Lead, Contact, Account, Opportunity. It can be useful as queryset method, but I am not sure how it supports multiple databases. Beatbox is an extraneus element that frequently willl be not installed. I would recommend to put the code to a new `salesforce.util` or similar, until a volunteer would be interested in integration.

**Comment by philchristensen** [comment]
I agree. We're on the same page.

**Comment by tvanesse** [comment]
Ok I'm on it. I should be able to provide a pull request in a few days.

**Comment by tvanesse** [comment]
See pull request #96 for a working implementation. There are things that could be improved, for instance:

* support for custom required fields on `Account` or `Contact` (see comments in the code)
* additional keyword args to use all the endpoint capabilities

To be continued I guess.
